import i18n from 'i18next';
import { initReactI18next } from 'react-i18next';

const en = {
  translation: {
    // Common
    app_name: 'Sri Siva Sai Seeds',
    loading: 'Loading...',
    save: 'Save', cancel: 'Cancel', confirm: 'Confirm', delete: 'Delete',
    edit: 'Edit', view: 'View', approve: 'Approve', reject: 'Reject',
    submit: 'Submit', search: 'Search', filter: 'Filter', download: 'Download',
    yes: 'Yes', no: 'No', ok: 'OK', close: 'Close', back: 'Back',
    success: 'Success', error: 'Error', warning: 'Warning', info: 'Info',
    status: 'Status', date: 'Date', amount: 'Amount', quantity: 'Quantity',
    actions: 'Actions', details: 'Details', name: 'Name', phone: 'Phone',
    email: 'Email', address: 'Address', password: 'Password',

    // Auth
    login: 'Login', logout: 'Logout', register: 'Register',
    farmer_login: 'Farmer Login', admin_login: 'Manager Login', super_admin_login: 'Super Admin Login',
    mobile_number: 'Mobile Number', send_otp: 'Send OTP', verify_otp: 'Verify OTP',
    forgot_password: 'Forgot Password', remember_me: 'Remember Me',
    otp_sent: 'OTP sent to your mobile number',
    registration_pending: 'Registration submitted. Awaiting admin approval.',
    welcome_back: 'Welcome Back!', sign_in_desc: 'Sign in to your Sri Siva Sai Seeds account',
    sign_in: 'Sign In',

    // Nav / Landing
    market_rates_nav: 'Market Rates',
    seeds_catalog_nav: 'Seeds Catalog',
    how_it_works_nav: 'How It Works',
    features_nav: 'Features',
    go_to_dashboard: 'Go to Dashboard',
    hero_title: 'Modern Farming, Smarter Markets',
    hero_subtitle: 'Sri Siva Sai Seeds connects farmers with verified seeds, live market prices and transparent grain trading — all in one platform.',
    get_started: 'Get Started',
    view_market_rates: 'View Market Rates',
    trusted_by: 'Trusted by farmers across Telangana',
    live_market_prices: 'Live Market Prices',
    live_market_desc: 'Admin-updated grain prices by grade. Know exactly what you\'ll earn before you sell.',
    explore_seeds: 'Explore Seeds Catalog',
    available_seeds: 'Available Seeds',
    seeds_desc: 'Purchase certified seeds with quality assurance and transparent pricing.',
    browse_catalog: 'Browse Catalog',
    how_it_works: 'How It Works',
    how_it_works_desc: 'Three simple steps to get started with Sri Siva Sai Seeds.',
    register_step: 'Register & Get Approved',
    register_step_desc: 'Create your farmer account and get verified by admin within 24 hours.',
    browse_step: 'Browse & Decide',
    browse_step_desc: 'Check live market prices, browse seed catalog, and plan your operations.',
    trade_step: 'Buy & Sell with Confidence',
    trade_step_desc: 'Purchase seeds or submit grain sales. All transactions are verified and secure.',
    why_agriflow: 'Why Sri Siva Sai Seeds?',
    fair_prices: 'Fair Prices', fair_prices_desc: 'Transparent pricing updated daily by verified admins.',
    verified_seeds: 'Verified Seeds', verified_seeds_desc: 'All seeds are quality-checked and certified.',
    fast_payments: 'Fast Payments', fast_payments_desc: 'Get paid quickly once your grain sale is approved.',
    expert_support: 'Expert Support', expert_support_desc: 'Our team visits your farm and guides you through every step.',
    start_journey: 'Start Your Journey',
    get_started: 'Get started',
    get_started_subtitle: 'How would you like to proceed?',
    register_free: 'Register Free',
    already_farmer: 'Already a farmer?',
    need_credentials: 'New to Sri Siva Sai Seeds?',
    need_credentials_desc: 'Get in touch with our team to register your farm and receive your login credentials.',
    call_us: 'Call Us',
    visit_us: 'Visit Us',
    office_address: 'Sri Siva Sai Seeds, Kurnool, Andhra Pradesh, 518004',

    // Portal Pages (Admin / Manager)
    dashboard: 'Dashboard', farm_overview: 'Farm Overview',
    crops_cycles: 'Crops & Cycles', booking_slot: 'Booking Slot',
    transaction_history: 'Transaction History', seed_purchase: 'Seed Purchase',
    grain_sales: 'Grain Sales', profile_settings: 'Profile / Settings',
    farmers: 'Farmers', warehouse: 'Warehouse Management',
    reports: 'Reports & Analytics', seeds_inventory: 'Seeds Inventory',
    farm_visits: 'Farm Visits', market_rates: 'Market Rates',
    manage_admins: 'Managers', audit_logs: 'Audit Logs', settings: 'Settings',

    // Dashboard stats
    total_farmers: 'Total Farmers', active_fields: 'Active Fields',
    total_revenue: 'Total Revenue', warehouse_capacity: 'Warehouse Capacity',
    active_farmers: 'Active Farmers', pending_approvals: 'Pending Approvals',
    recent_transactions: 'Recent Transactions', monthly_revenue: 'Monthly Revenue',
    quick_actions: 'Quick Actions', add_farmer: 'Add Farmer',
    set_market_rate: 'Set Market Rate', view_reports: 'View Reports',
    manage_warehouse: 'Manage Warehouse',

    // Farmers directory
    farmers_directory: 'Farmers Directory',
    farmer_management: 'Farmer Management',
    registered_farmers: 'Registered Farmers',
    pending_verification: 'Pending Verification',
    export_csv: 'Export CSV',
    all_statuses: 'All Statuses',
    no_farmers_found: 'No farmers found',
    farmer_details: 'Farmer Details',
    bank_account: 'Bank Account',
    not_provided: 'Not provided',

    // Seeds inventory
    add_seed: 'Add Seed', update_stock: 'Update Stock',
    price_per_kg: 'Price/kg', available_stock: 'Available Stock',
    in_stock: 'In Stock', out_of_stock: 'Out of Stock',
    stock_kg: 'Stock (kg)', is_active: 'Active',

    // Crop
    crop_type: 'Crop Type', acres: 'Acres', sowing_date: 'Sowing Date',
    harvest_date: 'Harvest Date', crop_status: 'Crop Status', add_crop: 'Add Crop',
    crop_cycle: 'Crop Cycle', month: 'Month', growing: 'Growing',
    harvested: 'Harvested', failed: 'Failed', sold: 'Sold',
    register_crop: 'Register Crop', crop_details: 'Crop Details',
    visit_month_1: 'Month 1: Verification Visit', visit_month_3: 'Month 3: Progress Visit',

    // Seeds
    seed_name: 'Seed Name', variety: 'Variety',
    quantity_kg: 'Quantity (kg)', total_amount: 'Total Amount',
    upi_id: 'UPI ID', transaction_id: 'Transaction ID', invoice: 'Invoice',
    purchase_seeds: 'Purchase Seeds',

    // Grain
    grain_type: 'Grain Type', grade: 'Grade', grade_a: 'Grade A',
    grade_b: 'Grade B', grade_c: 'Grade C', raw_material: 'Raw Material (kg)',
    wastage: 'Wastage (kg)', good_material: 'Good Material (kg)',
    estimated_amount: 'Estimated Amount', submit_sale: 'Submit Sale',

    // Slot
    booking_date: 'Booking Date', delivery_address: 'Delivery Address',
    warehouse_address: 'Warehouse Address', available_capacity: 'Available Capacity',
    book_slot: 'Book Slot',

    // Market rates
    set_rate: 'Set Rate', price_per_kg_label: 'Price per kg (₹)',
    effective_date: 'Effective Date', crop_name: 'Crop Name',
    current_rates: 'Current Rates',

    // Warehouse
    warehouse_name: 'Warehouse Name', location: 'Location',
    total_capacity: 'Total Capacity', used_capacity: 'Used Capacity',
    available: 'Available', add_warehouse: 'Add Warehouse',

    // Profile
    bank_details: 'Bank Details', bank_name: 'Bank Name',
    account_number: 'Account Number', ifsc_code: 'IFSC Code',
    change_request_pending: 'Change request pending admin approval',
    request_bank_change: 'Request Bank Detail Change',
    acres_of_land: 'Acres of Land', crop_address: 'Crop/Farm Location',

    // Status badges
    pending: 'Pending', active: 'Active', approved: 'Approved',
    rejected: 'Rejected', completed: 'Completed', confirmed: 'Confirmed',
    cancelled: 'Cancelled', paid: 'Paid', failed_status: 'Failed',

    // Language
    language: 'Language', english: 'English', telugu: 'తెలుగు', hindi: 'हिंदी',

    // Notifications
    notifications: 'Notifications', no_notifications: 'No new notifications',
    mark_all_read: 'Mark all as read',

    // Chatbot
    chatbot: 'Market Assistant', ask_market: 'Ask about market prices...',
    price_forecast: 'Price Forecast',

    // Super Admin
    global_farmer_directory: 'Global Farmer Directory',
    read_only_view: 'Read-only view of all registered farmers',
    manage_admins_desc: 'Create and manage manager accounts',
    create_admin: 'Create Admin',
    system_audit_logs: 'System Audit Logs',
    audit_logs_desc: 'Track all critical actions performed by admins and managers',
    operational_portal: 'Operational Portal',
    
    // Form & Auth Additions
    full_name: 'Full Name *', your_full_name: 'Your full name',
    email_optional: 'Email (Optional)', your_email: 'your@email.com',
    min_8_chars: 'Min. 8 chars', confirm_password: 'Confirm Password *', repeat_password: 'Repeat password',
    enter_6_digit_otp: 'Enter 6-digit OTP', resend_otp_in: 'Resend OTP in',
    didnt_receive_code: "Didn't receive code?", resend_otp: 'Resend OTP',
    home_address_placeholder: 'Your home/mailing address', eg_5_5: 'e.g. 5.5',
    crop_address_placeholder: 'Village/Survey No./GPS location of your farm',
    registration_review_msg: '⏳ Your registration will be reviewed by an Admin before activation. You\'ll receive a notification once approved.',
    submitting: 'Submitting...', submit_registration: 'Submit Registration',
    already_have_account: 'Already have an account?', login_here: 'Login here',
    create_farmer_account: 'Create Farmer Account', join_agriflow: 'Join Sri Siva Sai Seeds and start managing your farm',
    personal_info: 'Personal Info', verify_otp_step: 'Verify OTP', farm_details: 'Farm Details',
    please_fill_all_fields: 'Please fill all fields', login_failed: 'Login failed',
    agricultural_partner: 'Your Agricultural Partner', crop_tracking: 'Crop Tracking',
    crop_tracking_desc: '4-month cycle monitoring', grain_sales_title: 'Grain Sales',
    grain_sales_desc: 'Grade-based pricing', seed_purchase_title: 'Seed Purchase',
    seed_purchase_desc: 'Premium seed varieties', market_rates_title: 'Market Rates',
    market_rates_desc: 'Real-time price updates', back_to_home: 'Back to Home',
    mobile_placeholder: '10-digit mobile number', password_placeholder: 'Enter password',
    signing_in: 'Signing in...', new_farmer: 'New farmer?',
    demo_farmer_msg: '🌾 Demo Farmer: Register a new account or ask your admin for credentials.',
    passwords_do_not_match: 'Passwords do not match', enter_valid_phone: 'Enter valid 10-digit phone',
    invalid_otp: 'Invalid OTP', fill_all_details: 'Fill all farm details',
    manager_portal: 'Manager Portal', agriflow_erp_admin: 'Sri Siva Sai Seeds Administration',
    login_as_manager: 'Login as Manager', manager_default_creds: '🔒 Default: phone=8888888888, password=Manager@123',
    reset_password: 'Reset Password', recover_access_desc: 'Recover access to your Sri Siva Sai Seeds account',
    enter_mobile_number: 'Enter your mobile number', send_reset_otp: 'Send Reset OTP',
    enter_otp_sent_to: 'Enter OTP sent to', set_new_password: 'Set New Password',
    new_password_placeholder: 'New password (min. 8 chars)', confirm_new_password_placeholder: 'Confirm new password',
    resetting: 'Resetting...', back_to_login: 'Back to Login', phone_not_registered: 'Phone not registered',
    password_min_8: 'Password must be at least 8 characters', password_reset_success: 'Password reset successfully!',
    super_admin_portal: 'Super Admin Portal', login_as_super_admin: 'Login as Super Admin',
    super_admin_default_creds: '🔒 Default: phone=9999999999, password=Super@123',
    india_agri_market: "India's Agricultural Marketplace", buy_seeds_hero: "Buy Seeds", sell_grains_hero: "Sell Grains",
    grow_better: "Grow Better", hero_desc_full: "Browse live market rates, explore premium seed varieties, and connect with verified warehouses. Register to start buying or selling — it's free for farmers.",
    buy_seeds_btn: "Buy Seeds", sell_grains_btn: "Sell Grains", hero_badges: "✓ Easy registration  ·  ✓ No hidden charges  ·  ✓ Admin verified",
    footer_copyright: "© 2026 Sri Siva Sai Seeds. Empowering Indian Farmers.",
    // Farmer Dashboard
    total_earned: 'Total Earned', seed_investment: 'Seed Investment', upcoming_visits: 'Upcoming Visits',
    four_month_cycle: '4-Month Crop Cycle', upcoming_farm_visits: 'Upcoming Farm Visits',
    no_visits_scheduled: 'No visits scheduled', month_visit: 'Month {{month}} Visit', date_tbd: 'Date TBD',
    recent_crops: 'Recent Crops', view_all: 'View all', no_crops_registered: 'No crops registered yet',
    sowed: 'Sowed', recent_transactions: 'Recent Transactions', no_transactions_yet: 'No transactions yet',
    register_crop: 'Register Crop', book_slot: 'Book Slot',
    morning: 'Morning', afternoon: 'Afternoon', evening: 'Evening', good_greeting: 'Good {{time}}',
    dashboard_manage_desc: 'Manage your farm, crops and transactions from your dashboard.',
    // Crop Management
    sowing: 'Sowing', growth: 'Growth', maturity: 'Maturity', harvest: 'Harvest', growing: 'Growing',
    verification_visit: 'Verification Visit', monitoring: 'Monitoring', progress_visit: 'Progress Visit',
    ready_to_sell: 'Ready to sell', active_growth: 'Active growth',
    crop_management_desc: 'Manage your crop registrations and track growth cycles',
    no_crops_yet: 'No crops registered yet', register_first_crop: 'Register your first crop to start tracking',
    farm_visits: 'Farm Visits', fill_crop_details: 'Fill in your crop details',
    farm_visits_auto_scheduled: '📅 Farm visits will be auto-scheduled for Month 1 (verification) and Month 3 (progress check).',
    registering: 'Registering...', enter_valid_acreage: 'Enter valid acreage',
    crop_registered_success: 'Crop registered! Visits scheduled for Month 1 and 3.',
    acres_placeholder: 'Number of acres (e.g. 4.5)',
    // Seed Purchase
    seed_purchase_desc_subtitle: 'Browse and purchase premium seeds from admin inventory',
    browse_seeds: 'Browse Seeds', purchase_history: 'Purchase History', search_seeds_placeholder: 'Search seeds by name or variety...',
    purchase: 'Purchase', no_purchases_yet: 'No purchases yet', order_summary: 'Order Summary',
    processing: 'Processing...', confirm_purchase: 'Confirm Purchase', enter_valid_quantity: 'Enter valid quantity',
    max_available: 'Max available', quantity_kg_placeholder: 'Quantity in kg',
    // Grain Sales
    grain_sales_desc: 'Submit grains for sale and track approval status', new_sale: 'New Sale',
    todays_market_rates: "Today's Market Rates", my_grain_sales: 'My Grain Sale Requests',
    no_grain_sales_yet: 'No grain sales submitted yet', submit_grain_sale: 'Submit Grain Sale',
    good_material_counts_desc: 'Only good material counts towards payment',
    link_to_crop: 'Link to Crop (Optional)', estimated_payment: 'Estimated Payment',
    wastage_note: 'Wastage is not counted in payment. Final amount subject to admin verification.',
    submit_sale_request: 'Submit Sale Request', enter_good_material: 'Enter good material quantity',
    // Layout
    farmer_portal: 'Farmer Portal',
    // Booking Slot
    booking_slot_desc: 'Schedule grain deliveries to warehouses', my_booking_slots: 'My Booking Slots',
    no_slots_booked_yet: 'No slots booked yet', schedule_grain_delivery: 'Schedule grain delivery to warehouse',
    booking: 'Booking...', confirm_booking: 'Confirm Booking', warehouse: 'Warehouse', delivery_address: 'Delivery Address',
    // Transaction History
    transaction_history_desc: 'View all your payments and receipts', export_csv: 'Export CSV',
    total_spent: 'Total Spent', total_transactions: 'Total Transactions', search_tx_placeholder: 'Search by description, UPI ID or invoice...',
    no_transactions_found: 'No transactions found', type: 'Type', description: 'Description',
    // Profile
    profile_settings_desc: 'Manage your personal and banking information', personal_info: 'Personal Information',
    edit: 'Edit', farm_location: 'Farm Location', saving: 'Saving...', save_changes: 'Save Changes',
    agri_details: 'Agricultural Details', land_size: 'Land Size (Acres)', soil_type: 'Soil Type',
    irrigation_type: 'Irrigation Type', primary_crop: 'Primary Crop', secondary_crop: 'Secondary Crop (Optional)',
    required_documents: 'Required Documents', aadhaar_card: 'Aadhaar Card Copy', bank_passbook: 'Bank Passbook Copy',
    land_ownership: 'Land Ownership Proof',
    // SuperAdmin Dashboard
    system_overview: 'System Overview', platform_stats_desc: 'Platform-wide statistics and activity',
    system_status: 'System Status', all_systems_operational: 'All Systems Operational',
    total_farmers: 'Total Farmers', system_managers: 'System Managers', farm_visits_recorded: 'Farm Visits Recorded',
    active_warehouses: 'Active Warehouses', weekly_activity: 'Weekly Platform Activity', recent_logins: 'Recent Admin Logins',
    active_warehouses: 'Active Warehouses', weekly_activity: 'Weekly Platform Activity', recent_logins: 'Recent Admin Logins',
    manager_user: 'Manager User', just_now: 'Just now', hours_ago: 'h ago', daily_logins: 'Daily Logins', new_farmers: 'New Farmers',
    // Admin Dashboard
    system_overview_desc: 'System overview and analytics', active_farmers: 'Active Farmers', active_crop_cycles: 'Active Crop Cycles',
    procurement_mtd: 'Procurement (MTD)', warehouse_inv: 'Warehouse Inv.', total_revenue_mtd: 'Total Revenue (MTD)',
    net_profit_mtd: 'Net Profit (MTD)', pending_payments: 'Pending Payments', visitors_today: 'Visitors Today',
    monthly_revenue: 'Monthly Revenue', warehouse_capacity: 'Warehouse Capacity', used: 'used',
    action_required: 'Action Required', pending_registration: 'Pending Registration', farmers_waiting_approval: 'Farmers waiting for approval',
    review: 'Review', pay_farmer: 'Pay Farmer', paid: 'Paid',
    mr_grade_available: "Available Grades", available_status: "Available", account_details: "Account Details", cache_management: "Cache Management", billing_invoices: "Billing & Invoices", grain_procurement: "Grain Procurement", qtl: "Qtl",
    rice: "Rice", wheat: "Wheat", maize: "Maize", cotton: "Cotton", sugarcane: "Sugarcane", groundnut: "Groundnut", bajra: "Bajra", red_gram: "Red Gram",
    mr_live_prices: "Live Prices", mr_hero_title: "Today's Market Rates", mr_hero_desc: "Real-time grain prices by grade — updated by admin. Browse all crops and grades below.", mr_grain_price_index: "Grain Price Index", mr_filter_desc: "Filter by crop type to see per-kg rates for all grades", mr_sell_your_grains: "Sell Your Grains", mr_all_crops: "All Crops", mr_price_per_kg: "Price per kg", mr_grade_premium: "Premium", mr_grade_standard: "Standard", mr_grade_basic: "Basic", mr_sell_btn: "Sell", mr_no_rates: "Market rates will appear here once set by admin", mr_cta_title: "Ready to sell your grain?", mr_cta_desc: "Register as a farmer and submit your harvest at the best prices.", mr_get_started: "Get Started", sc_premium_quality: "Premium Quality Seeds", sc_hero_title: "Seeds Catalog", sc_hero_desc: "Admin-verified premium seed varieties for every crop type. Buy with confidence.", sc_search_placeholder: "Search seeds by name or variety...", sc_browse_buy: "Browse & Buy Seeds", sc_verified: "Verified", sc_in_stock: "In Stock", sc_buy_now: "Buy Now", sc_kg_left: "kg left", sc_no_seeds: "Seeds catalog will appear here", sc_no_match: "No seeds matched your search", sc_cta_title: "Ready to buy premium seeds?", sc_cta_desc: "Register as a farmer to place orders and get seeds delivered directly.", sc_get_started: "Get Started", hiw_simple_process: "Simple Process", hiw_hero_title: "How Sri Siva Sai Seeds Works", hiw_hero_desc: "A transparent, easy-to-use platform connecting farmers with fair markets and premium supplies.", hiw_step1_title: "Register & Get Approved", hiw_step1_desc: "Register as a new farmer by providing personal and farming details. Once saved, become part of the verified network and can access all platform services.", hiw_step2_title: "Browse & Decide", hiw_step2_desc: "Once approved, login to access the full dashboard. Check live, admin-updated market rates for all crops and grades. Explore our extensive catalog of verified seeds and check warehouse capacities.", hiw_step3_title: "Buy or Sell", hiw_step3_desc: "Ready to act? Purchase seeds directly through the platform or submit your grain harvest. All transactions are secure, verified by admins, and backed by a full digital trail.", hiw_start_journey: "Start Your Journey", feat_platform: "Comprehensive Platform", feat_hero_title: "Everything a Farmer Needs", feat_hero_desc: "Discover the powerful tools and features designed to streamline your agricultural operations from seed to sale.", feat_cta_title: "Ready to access these features?", feat_cta_desc: "Join the Sri Siva Sai Seeds community today and take your farming operations to the next level with our complete suite of tools.", feat_create_account: "Create Free Account",
    feat1_title: "Live Market Rates", feat1_desc: "Real-time crop prices updated by district managers for all grades (A, B, C). Make informed decisions before selling your harvest.",
    feat2_title: "Seed Purchasing", feat2_desc: "Order premium seeds online from verified suppliers. Pay securely via UPI and receive digital invoices instantly for your records.",
    feat3_title: "Crop Tracking", feat3_desc: "Register your crops and track their entire 4-month growing cycle. Get support through scheduled farm visits from our agricultural experts.",
    feat4_title: "Warehouse Booking", feat4_desc: "Book delivery slots at nearby verified warehouses. See real-time capacity information to ensure your grain is stored safely without wait times.",
    feat5_title: "Secure Payments", feat5_desc: "All transactions are verified by administrators. Enjoy secure UPI-based payments with full transparency and a complete digital invoice trail.",
    feat6_title: "24/7 Access", feat6_desc: "Your farm management doesn't sleep, and neither do we. Check prices, manage crops, and review your transaction history anytime, anywhere.",
    hiw_card1_title: "Farmer Verification", hiw_card1_subtitle: "Approved within 24 hours", hiw_card1_name: "Name", hiw_card1_village: "Village", hiw_card1_acres: "Acres", hiw_card1_status: "Status", hiw_card1_verified: "Account verified & activated",
    hiw_card2_title: "Live Market Rates", hiw_card2_subtitle: "Updated by Admin", hiw_card2_live: "Live", hiw_card2_grade: "Grade",
    hiw_card3_title: "Transaction Summary", hiw_card3_subtitle: "Verified & Secured", hiw_card3_grain: "Grain Type", hiw_card3_qty: "Quantity", hiw_card3_rate: "Rate", hiw_card3_total: "Total Earnings", hiw_card3_payment: "Payment processed securely",
    grade_label: "Grade", footer_market_rates: "Market Rates", footer_seeds: "Seeds", footer_farmer_login: "Farmer Login", footer_manager_login: "Manager Login",
    india_agri_marketplace: "India's Agricultural Marketplace", buy_seeds_btn_short: "Buy Seeds", sell_grains_btn_short: "Sell Grains",
    visit_today: "Farm visit is TODAY!", visit_tomorrow: "Farm visit is TOMORROW!", visit_in_2_days: "Farm visit in 2 days", field_officer_msg_pt1: "A field officer will visit your farm on", field_officer_msg_pt2: "Please be available at your field.",
    today_excl: "Today!", tomorrow: "Tomorrow", in_2_days: "In 2 days", days_away: "days away", view_all: "View all",
    insufficient_capacity: "Insufficient warehouse capacity! Available: {{capacity}}T", fill_required: "Fill all required fields", booking_created: "Booking slot created! Awaiting manager confirmation.", booking_failed: "Booking failed",
    used_colon: "Used:", available_colon: "Available:", total_colon: "Total:", select_warehouse: "Select warehouse", warehouse_available: "{{name}} (Available: {{capacity}}T)",
    quantity_in_kg: "Quantity in kg", exceeds_capacity: "Exceeds available warehouse capacity ({{capacity}}T available)", booking_details: "Booking Details", booking_id_upper: "BOOKING ID",
    date_upper: "DATE", grain_type_upper: "GRAIN TYPE", quantity_upper: "QUANTITY", warehouse_upper: "WAREHOUSE", status_upper: "STATUS", delivery_address_upper: "DELIVERY ADDRESS",
    acres_lower: "acres", registering: "Registering...", failed_to_register_crop: "Failed to register crop",
    enter_valid_quantity: "Enter valid quantity", grain_sale_submitted: "Grain sale submitted!", submission_failed: "Submission failed", manager_assign_slot_desc: "Manager will assign slot for checking grains.", submitting: "Submitting...",
    profile_updated: "Profile updated!", update_failed: "Update failed", agri_details_updated: "Agricultural details updated!", file_size_limit: "File must be under 5MB", uploading_file: "Uploading {{name}}...",
    file_uploaded_success: "File uploaded successfully", upload_failed: "Upload failed", fill_bank_fields: "Fill all bank fields", bank_change_submitted: "Bank change request submitted. Admin will review it.", request_failed: "Request failed",
    not_set: "Not set", soil_type_placeholder: "e.g. Black Cotton, Red", select_option: "Select...", drip: "Drip", sprinkler: "Sprinkler", flood: "Flood", rainfed: "Rainfed", other: "Other",
    primary_crop_placeholder: "e.g. Cotton, Rice", secondary_crop_placeholder: "Intercrop or rotation", request_change: "Request Change", bank_detail_change_warning: "Bank detail changes require admin approval before taking effect.",
    sbi_placeholder: "e.g. SBI", ifsc_placeholder: "e.g. SBIN0001234", account_number_placeholder: "Account number", upi_placeholder: "yourname@upi", approval_status: "Approval Status",
    doc_format_desc: "PDF or Image format", bank_passbook_desc: "Front page showing account details", land_ownership_desc: "Patta / RoR / Title Deed", view_uploaded_doc: "View Uploaded Document", re_upload: "Re-upload", upload: "Upload",
    invalid_upi_id: "Invalid UPI ID format", purchase_successful: "Purchase successful! Invoice: {{invoice}} | Amount: ₹{{amount}}", validation_failed: "Validation failed: {{errors}}", purchase_failed: "Purchase failed",
    filters: "Filters", clear_all: "Clear All", price_range: "Price Range", crop_type: "Crop Type", availability: "Availability", in_stock_only: "In Stock Only", no_seeds_found: "No seeds found",
    adjust_filters_desc: "Try adjusting your filters or search query to find what you're looking for.", clear_all_filters: "Clear All Filters", pay_at_warehouse: "Pay at Warehouse", payment_method: "Payment Method",
    pay_now_upi: "Pay Now (UPI)", warehouse_payment_warning: "⚠️ Stock will be reserved for 24 hours. If not paid at the warehouse, the order will be cancelled.", processing: "Processing...",
    all: "All", credit: "Credit", debit: "Debit", no_logs_found: "No transactions to download",
    tx_type: "Type", tx_date: "Date", tx_ref: "Reference", tx_amount: "Amount", tx_status: "Status",
    payment_processed_successfully: "Payment processed successfully", payment_failed: "Payment failed", pay_farmer: "Pay Farmer",
    system_overview_desc: "System Overview and KPIs", total_farmers: "Total Farmers", active_farmers: "Active Farmers", active_crop_cycles: "Active Crop Cycles",
    procurement_mtd: "Procurement (MTD)", warehouse_inv: "Warehouse Inv.", total_revenue_mtd: "Total Revenue (MTD)", net_profit_mtd: "Net Profit (MTD)", pending_payments: "Pending Payments",
    visitors_today: "Visitors Today", monthly_revenue: "Monthly Revenue", warehouse_capacity: "Warehouse Capacity", used: "Used", action_required: "Action Required",
    pending_registration: "Pending Registration", farmers_waiting_approval: "Farmers waiting for approval", review: "Review", recent_transactions: "Recent Transactions", paid: "Paid",
    slot_marked_as: "Slot marked as {{status}}", action_failed: "Action failed", no_grain_sale_linked: "No grain sale linked to this booking", farmer_paid_successfully: "Farmer paid successfully",
    payment_already_processed: "Payment already processed or transaction not found", enter_valid_quantities: "Enter valid quantities", quantities_cannot_be_negative: "Quantities cannot be negative",
    good_bad_must_equal_total: "Good + Bad must equal total", select_rejection_reason: "Please select a rejection reason for bad produce", inspection_saved: "Inspection saved! Admin has been notified.",
    inspection_failed: "Inspection failed", enter_valid_non_negative: "Enter valid non-negative quantities", yield_updated_success: "Yield updated successfully! Admins notified.", failed_to_update_yield: "Failed to update yield",
    good_qty_kg: "Good: {{qty}} kg", waste_qty_kg: "Waste: {{qty}} kg", view_details: "View Details", edit_good_waste_yield: "Edit Good/Waste Yield", confirm_and_assign_slot: "Confirm & Assign Slot",
    inspect: "Inspect", pay: "Pay", booked_on: "Booked On", delivery_date: "Delivery Date", sale_id: "Sale ID", total_quantity: "Total Quantity", inspection_report: "Inspection Report",
    good_quality: "Good Quality", rejected: "Rejected", rejection_reason: "Rejection Reason", inspector_notes: "Inspector Notes", inspector: "Inspector", crop_inspection: "Crop Inspection",
    total_lower: "total", total_received: "Total Received", entered: "Entered", good_quality_qty: "Good Quality Quantity (kg)", rejected_bad_quality_qty: "Rejected / Bad Quality (kg)",
    reason_for_rejection: "Reason for Rejection", select_reason_placeholder: "— Select reason —", inspection_notes_optional: "Inspection Notes (optional)", additional_observations: "Any additional observations…",
    save_inspection: "Save Inspection", edit_yield: "Edit Yield", update_good_waste_seed: "Update good and waste seed", good_seed_kg: "Good Seed (kg)", waste_seed_kg: "Waste Seed (kg)",
    updating: "Updating...", update: "Update", assign_time_slot: "Assign Time Slot", assign_slot_confirm_booking: "Assign a slot and confirm the booking", select_time_slot_for: "Select Time Slot for",
    loading_slots: "Loading slots...", no_time_slots_available: "No time slots available for this date and warehouse.", full: "FULL", kg_available_count: "{{count}} kg available", confirm_booking: "Confirm Booking",
    pending: "Pending", confirmed: "Confirmed", delivered: "Delivered to Warehouse", inspection_completed: "Inspection Completed", completed: "Completed", cancelled: "Cancelled",
    saving: "Saving...", booking_details: "Booking Details", booking_id: "Booking ID", available: "AVAILABLE",
    active: "Active", dispatch_success: "Successfully dispatched {{quantity}}kg of {{grain}} to {{name}}",
    logs_downloaded: "Logs downloaded successfully", no_logs_found_to_download: "No event logs to download",
    all: 'All', credit: 'Credit', debit: 'Debit',
    export_report: 'Export Report', search_logs_placeholder: 'Search by action or farmer...', timestamp: 'Timestamp', manager: 'Manager', action: 'Action', entity_affected: 'Farmer / Entity', details: 'Details', no_logs_found: 'No logs found',
    revenue_by_month: 'Revenue by Month',
    active_crop_distribution: 'Active Crop Distribution',
    farmer_registration_data: 'Farmer Registration Data',
    farmer_registration_data_desc: 'Details of registered farmers',
    transaction_ledger: 'Transaction Ledger',
    transaction_ledger_desc: 'Detailed transaction history',
    warehouse_inventory_logs: 'Warehouse Inventory Logs',
    warehouse_inventory_logs_desc: 'Logs for warehouse inventory',
    super_admin_portal: 'Super Admin Portal',
    event_logs: 'Event Logs',
    event_logs_desc: 'View all actions and work done by managers',
    account_information: 'Account Information',
    change_password: 'Change Password',
    use_strong_password: 'Use a strong password with a mix of letters, numbers and symbols.',
    current_password: 'Current Password',
    enter_current_password: 'Enter your current password',
    new_password: 'New Password',
    at_least_8_chars: 'At least 8 characters',
    one_uppercase_letter: 'One uppercase letter',
    one_number: 'One number',
    one_special_char: 'One special character',
    download_report: 'Download Report',
    filters: 'Filters',
    clear_all: 'Clear All',
    price_range: 'Price Range',
    availability: 'Availability',
    delivered_to_warehouse: 'Delivered to Warehouse',
    inspection_completed: 'Inspection Completed',
  }
};

const te = {
  translation: {
    app_name: 'శ్రీ శివ సాయి సీడ్స్',
    loading: 'లోడవుతోంది...', save: 'సేవ్ చేయి', cancel: 'రద్దు', confirm: 'నిర్ధారించు',
    delete: 'తొలగించు', edit: 'సవరించు', view: 'చూడు', approve: 'ఆమోదించు', reject: 'తిరస్కరించు',
    submit: 'సమర్పించు', search: 'వెతుకు', filter: 'వడపోత', download: 'డౌన్‌లోడ్',
    yes: 'అవును', no: 'లేదు', ok: 'సరే', close: 'మూసు', back: 'వెనక్కి',
    success: 'విజయం', error: 'లోపం', warning: 'హెచ్చరిక', info: 'సమాచారం',
    status: 'స్థితి', date: 'తేదీ', amount: 'మొత్తం', quantity: 'పరిమాణం',
    actions: 'చర్యలు', details: 'వివరాలు', name: 'పేరు', phone: 'ఫోన్',
    email: 'ఇమెయిల్', address: 'చిరునామా', password: 'పాస్‌వర్డ్',
    login: 'లాగిన్', logout: 'లాగ్ అవుట్', register: 'నమోదు',
    farmer_login: 'రైతు లాగిన్', admin_login: 'నిర్వాహకుడు లాగిన్', super_admin_login: 'సూపర్ అడ్మిన్ లాగిన్',
    mobile_number: 'మొబైల్ నంబర్', send_otp: 'OTP పంపు', verify_otp: 'OTP ధృవీకరించు',
    forgot_password: 'పాస్‌వర్డ్ మర్చిపోయారా', remember_me: 'నన్ను గుర్తుంచుకో',
    otp_sent: 'మీ మొబైల్‌కు OTP పంపబడింది',
    registration_pending: 'నమోదు సమర్పించబడింది. నిర్వాహకుడి ఆమోదం కోసం వేచి ఉంది.',
    welcome_back: 'స్వాగతం!', sign_in_desc: 'మీ Sri Siva Sai Seeds ఖాతాలోకి సైన్ ఇన్ చేయండి',
    sign_in: 'సైన్ ఇన్',

    // Nav / Landing
    market_rates_nav: 'మార్కెట్ రేట్లు',
    seeds_catalog_nav: 'విత్తన కేటలాగ్',
    how_it_works_nav: 'ఇది ఎలా పని చేస్తుంది',
    features_nav: 'ఫీచర్లు',
    go_to_dashboard: 'డాష్‌బోర్డ్‌కు వెళ్ళు',
    hero_title: 'ఆధునిక వ్యవసాయం, స్మార్ట్ మార్కెట్లు',
    hero_subtitle: 'Sri Siva Sai Seeds రైతులను ధృవీకరించిన విత్తనాలు, లైవ్ మార్కెట్ ధరలు మరియు పారదర్శక ధాన్యం వ్యాపారంతో కలుపుతుంది.',
    get_started: 'ప్రారంభించండి',
    view_market_rates: 'మార్కెట్ రేట్లు చూడు',
    trusted_by: 'తెలంగాణ అంతటా రైతులు నమ్ముతున్నారు',
    live_market_prices: 'లైవ్ మార్కెట్ ధరలు',
    live_market_desc: 'అడ్మిన్ అప్‌డేట్ చేసిన ధాన్యం ధరలు. అమ్మే ముందే మీకు ఎంత వస్తుందో తెలుసుకోండి.',
    explore_seeds: 'విత్తన కేటలాగ్ చూడు',
    available_seeds: 'అందుబాటులో ఉన్న విత్తనాలు',
    seeds_desc: 'నాణ్యత హామీతో ధృవీకరించిన విత్తనాలు కొనండి.',
    browse_catalog: 'కేటలాగ్ చూడు',
    how_it_works: 'ఇది ఎలా పని చేస్తుంది',
    how_it_works_desc: 'Sri Siva Sai Seeds తో ప్రారంభించడానికి మూడు సులభ దశలు.',
    register_step: 'నమోదు & ఆమోదం పొందండి',
    register_step_desc: '24 గంటల్లో రైతు ఖాతా సృష్టించి అడ్మిన్ ద్వారా ధృవీకరించబడండి.',
    browse_step: 'చూసి నిర్ణయించుకోండి',
    browse_step_desc: 'లైవ్ మార్కెట్ ధరలు చెక్ చేయండి, విత్తన కేటలాగ్ చూడండి.',
    trade_step: 'నమ్మకంతో కొనండి & అమ్మండి',
    trade_step_desc: 'విత్తనాలు కొనండి లేదా ధాన్యం అమ్మకాలు సమర్పించండి.',
    why_agriflow: 'Sri Siva Sai Seeds ఎందుకు?',
    fair_prices: 'న్యాయమైన ధరలు', fair_prices_desc: 'ప్రతి రోజు అడ్మిన్లు అప్‌డేట్ చేసే పారదర్శక ధరలు.',
    verified_seeds: 'ధృవీకరించిన విత్తనాలు', verified_seeds_desc: 'అన్ని విత్తనాలు నాణ్యత పరీక్ష చేయబడతాయి.',
    fast_payments: 'వేగమైన చెల్లింపులు', fast_payments_desc: 'ధాన్యం అమ్మకం ఆమోదించిన తర్వాత వేగంగా చెల్లించబడుతుంది.',
    expert_support: 'నిపుణుల మద్దతు', expert_support_desc: 'మా బృందం మీ పొలాన్ని సందర్శించి మార్గనిర్దేశం చేస్తుంది.',
    start_journey: 'మీ యాత్ర ప్రారంభించండి',
    register_free: 'ఉచితంగా నమోదు చేసుకోండి',
    already_farmer: 'ఇప్పటికే రైతు అయినారా?',
    need_credentials: 'Sri Siva Sai Seedsకు కొత్తగా వచ్చారా?',
    need_credentials_desc: 'మీ పొలాన్ని నమోదు చేయడానికి మరియు మీ లాగిన్ ఆధారాలను పొందడానికి మా బృందాన్ని సంప్రదించండి.',
    call_us: 'కాల్ చేయండి',
    visit_us: 'మమ్మల్ని సందర్శించండి',
    office_address: 'శ్రీ శివ సాయి సీడ్స్, కర్నూలు, ఆంధ్రప్రదేశ్, 518004',

    dashboard: 'డాష్‌బోర్డ్', farm_overview: 'వ్యవసాయ అవలోకనం',
    crops_cycles: 'పంటలు & చక్రాలు', booking_slot: 'బుకింగ్ స్లాట్',
    transaction_history: 'లావాదేవీ చరిత్ర', seed_purchase: 'విత్తన కొనుగోలు',
    grain_sales: 'ధాన్యం అమ్మకాలు', profile_settings: 'ప్రొఫైల్ / సెట్టింగులు',
    farmers: 'రైతులు', warehouse: 'గిడ్డంగి నిర్వహణ',
    reports: 'నివేదికలు & విశ్లేషణలు', seeds_inventory: 'విత్తన నిల్వ',
    farm_visits: 'వ్యవసాయ సందర్శనలు', market_rates: 'మార్కెట్ రేట్లు',
    manage_admins: 'మేనేజర్లు', audit_logs: 'ఆడిట్ లాగ్‌లు', settings: 'సెట్టింగులు',
    total_farmers: 'మొత్తం రైతులు', active_fields: 'క్రియాశీల పొలాలు',
    total_revenue: 'మొత్తం ఆదాయం', warehouse_capacity: 'గిడ్డంగి సామర్థ్యం',
    active_farmers: 'క్రియాశీల రైతులు', pending_approvals: 'పెండింగ్ ఆమోదాలు',
    recent_transactions: 'ఇటీవలి లావాదేవీలు', monthly_revenue: 'నెలవారీ ఆదాయం',
    quick_actions: 'త్వరిత చర్యలు', add_farmer: 'రైతును జోడించు',
    set_market_rate: 'మార్కెట్ రేటు సెట్ చేయి', view_reports: 'నివేదికలు చూడు',
    manage_warehouse: 'గిడ్డంగి నిర్వహించు',
    farmers_directory: 'రైతుల డైరెక్టరీ',
    farmer_management: 'రైతు నిర్వహణ',
    registered_farmers: 'నమోదైన రైతులు',
    pending_verification: 'పెండింగ్ ధృవీకరణ',
    export_csv: 'CSV ఎగుమతి',
    all_statuses: 'అన్ని స్థితులు',
    no_farmers_found: 'రైతులు కనుగొనబడలేదు',
    farmer_details: 'రైతు వివరాలు',
    bank_account: 'బ్యాంక్ ఖాతా',
    not_provided: 'అందించబడలేదు',
    add_seed: 'విత్తనం జోడించు', update_stock: 'నిల్వ అప్‌డేట్ చేయి',
    price_per_kg: 'కేజీకి ధర', available_stock: 'అందుబాటులో ఉన్న నిల్వ',
    in_stock: 'నిల్వలో ఉంది', out_of_stock: 'నిల్వ లేదు',
    stock_kg: 'నిల్వ (కేజీ)', is_active: 'క్రియాశీల',
    crop_type: 'పంట రకం', acres: 'ఎకరాలు', sowing_date: 'విత్తన తేదీ',
    add_crop: 'పంట జోడించు', register_crop: 'పంట నమోదు',
    seed_name: 'విత్తన పేరు', variety: 'రకం',
    grain_type: 'ధాన్యం రకం', grade: 'గ్రేడ్', grade_a: 'గ్రేడ్ A',
    grade_b: 'గ్రేడ్ B', grade_c: 'గ్రేడ్ C', raw_material: 'ముడి పదార్థం (కేజీ)',
    wastage: 'వ్యర్థం (కేజీ)', good_material: 'మంచి పదార్థం (కేజీ)',
    booking_date: 'బుకింగ్ తేదీ', delivery_address: 'డెలివరీ చిరునామా',
    set_rate: 'రేటు సెట్ చేయి', price_per_kg_label: 'కేజీకి ధర (₹)',
    effective_date: 'అమలు తేదీ', crop_name: 'పంట పేరు',
    current_rates: 'ప్రస్తుత రేట్లు',
    warehouse_name: 'గిడ్డంగి పేరు', location: 'స్థానం',
    total_capacity: 'మొత్తం సామర్థ్యం', used_capacity: 'వినియోగించిన సామర్థ్యం',
    available: 'అందుబాటులో', add_warehouse: 'గిడ్డంగి జోడించు',
    bank_details: 'బ్యాంక్ వివరాలు', bank_name: 'బ్యాంక్ పేరు',
    account_number: 'ఖాతా నంబర్', ifsc_code: 'IFSC కోడ్',
    change_request_pending: 'మార్పు అభ్యర్థన అడ్మిన్ ఆమోదం కోసం వేచి ఉంది',
    request_bank_change: 'బ్యాంక్ వివరాల మార్పు అభ్యర్థన',
    acres_of_land: 'భూమి ఎకరాలు', crop_address: 'పంట/వ్యవసాయ స్థలం',
    quantity_kg: 'పరిమాణం (కేజీ)', total_amount: 'మొత్తం మొత్తం',
    purchase_seeds: 'విత్తనాలు కొనుగోలు',
    book_slot: 'స్లాట్ బుక్ చేయి',
    pending: 'పెండింగ్', active: 'క్రియాశీల', approved: 'ఆమోదించబడింది',
    rejected: 'తిరస్కరించబడింది', completed: 'పూర్తయింది', confirmed: 'నిర్ధారించబడింది',
    cancelled: 'రద్దు చేయబడింది', paid: 'చెల్లించబడింది', failed_status: 'విఫలమైంది',
    language: 'భాష', english: 'English', telugu: 'తెలుగు', hindi: 'हिंदी',
    notifications: 'నోటిఫికేషన్‌లు', no_notifications: 'కొత్త నోటిఫికేషన్‌లు లేవు',
    mark_all_read: 'అన్నీ చదివినట్లు గుర్తించు',
    chatbot: 'మార్కెట్ సహాయకుడు', ask_market: 'మార్కెట్ ధరల గురించి అడగండి...',
    price_forecast: 'ధర అంచనా',
    global_farmer_directory: 'గ్లోబల్ రైతుల డైరెక్టరీ',
    read_only_view: 'నమోదైన రైతుల చదవడం మాత్రమే వీక్షణ',
    manage_admins_desc: 'మేనేజర్ ఖాతాలు సృష్టించండి మరియు నిర్వహించండి',
    create_admin: 'అడ్మిన్ సృష్టించు',
    system_audit_logs: 'సిస్టమ్ ఆడిట్ లాగ్‌లు',
    audit_logs_desc: 'అడ్మిన్లు మరియు మేనేజర్లు చేసిన అన్ని క్రిటికల్ చర్యలను ట్రాక్ చేయండి',
    operational_portal: 'ఆపరేషనల్ పోర్టల్',
    
    // Form & Auth Additions
    full_name: 'పూర్తి పేరు *', your_full_name: 'మీ పూర్తి పేరు',
    email_optional: 'ఇమెయిల్ (ఐచ్ఛికం)', your_email: 'your@email.com',
    min_8_chars: 'కనిష్టంగా 8 అక్షరాలు', confirm_password: 'పాస్‌వర్డ్ నిర్ధారించండి *', repeat_password: 'పాస్‌వర్డ్ పునరావృతం చేయండి',
    enter_6_digit_otp: '6 అంకెల OTP నమోదు చేయండి', resend_otp_in: 'లో OTP పంపబడుతుంది',
    didnt_receive_code: "కోడ్ రాలేదా?", resend_otp: 'OTP మళ్లీ పంపు',
    home_address_placeholder: 'మీ ఇంటి/మెయిలింగ్ చిరునామా', eg_5_5: 'ఉదాహరణకు 5.5',
    crop_address_placeholder: 'మీ పొలం యొక్క గ్రామం/సర్వే నంబర్/GPS స్థానం',
    registration_review_msg: '⏳ మీ నమోదు ఆక్టివేట్ చేయడానికి ముందు అడ్మిన్ ద్వారా సమీక్షించబడుతుంది. ఆమోదం పొందిన తర్వాత మీకు నోటిఫికేషన్ వస్తుంది.',
    submitting: 'సమర్పిస్తున్నాము...', submit_registration: 'నమోదు సమర్పించండి',
    already_have_account: 'ఇప్పటికే ఖాతా ఉందా?', login_here: 'ఇక్కడ లాగిన్ చేయండి',
    create_farmer_account: 'రైతు ఖాతాను సృష్టించండి', join_agriflow: 'Sri Siva Sai Seeds లో చేరి మీ వ్యవసాయాన్ని నిర్వహించడం ప్రారంభించండి',
    personal_info: 'వ్యక్తిగత సమాచారం', verify_otp_step: 'OTP ధృవీకరించు', farm_details: 'వ్యవసాయ వివరాలు',
    please_fill_all_fields: 'దయచేసి అన్ని ఫీల్డ్‌లను పూరించండి', login_failed: 'లాగిన్ విఫలమైంది',
    agricultural_partner: 'మీ వ్యవసాయ భాగస్వామి', crop_tracking: 'పంట ట్రాకింగ్',
    crop_tracking_desc: '4 నెలల చక్రం పర్యవేక్షణ', grain_sales_title: 'ధాన్యం అమ్మకాలు',
    grain_sales_desc: 'గ్రేడ్ ఆధారిత ధర', seed_purchase_title: 'విత్తనాల కొనుగోలు',
    seed_purchase_desc: 'ప్రీమియం విత్తనాల రకాలు', market_rates_title: 'మార్కెట్ రేట్లు',
    market_rates_desc: 'తాజా ధరల అప్‌డేట్స్', back_to_home: 'హోమ్‌కు తిరిగి వెళ్ళు',
    mobile_placeholder: '10 అంకెల మొబైల్ నంబర్', password_placeholder: 'పాస్‌వర్డ్ నమోదు చేయండి',
    signing_in: 'లాగిన్ అవుతున్నది...', new_farmer: 'కొత్త రైతా?',
    demo_farmer_msg: '🌾 డెమో రైతు: కొత్త ఖాతాను నమోదు చేసుకోండి లేదా మీ అడ్మిన్ ద్వారా వివరాలు తీసుకోండి.',
    passwords_do_not_match: 'పాస్‌వర్డ్‌లు సరిపోలడం లేదు', enter_valid_phone: 'సరైన 10 అంకెల ఫోన్ నంబర్‌ను నమోదు చేయండి',
    invalid_otp: 'చెల్లని OTP', fill_all_details: 'అన్ని వ్యవసాయ వివరాలను పూరించండి',
    manager_portal: 'మేనేజర్ పోర్టల్', agriflow_erp_admin: 'Sri Siva Sai Seeds అడ్మినిస్ట్రేషన్',
    login_as_manager: 'మేనేజర్‌గా లాగిన్ చేయండి', manager_default_creds: '🔒 డిఫాల్ట్: ఫోన్=8888888888, పాస్‌వర్డ్=Manager@123',
    reset_password: 'పాస్‌వర్డ్ రీసెట్ చేయండి', recover_access_desc: 'మీ Sri Siva Sai Seeds ఖాతాకు ప్రాప్యతను పునరుద్ధరించండి',
    enter_mobile_number: 'మీ మొబైల్ నంబర్ నమోదు చేయండి', send_reset_otp: 'రీసెట్ OTP పంపండి',
    enter_otp_sent_to: 'కు పంపిన OTP నమోదు చేయండి', set_new_password: 'కొత్త పాస్‌వర్డ్ సెట్ చేయండి',
    new_password_placeholder: 'కొత్త పాస్‌వర్డ్ (కనీసం 8 అక్షరాలు)', confirm_new_password_placeholder: 'కొత్త పాస్‌వర్డ్ నిర్ధారించండి',
    resetting: 'రీసెట్ అవుతున్నది...', back_to_login: 'లాగిన్‌కు తిరిగి వెళ్ళు', phone_not_registered: 'ఫోన్ నంబర్ నమోదు కాలేదు',
    password_min_8: 'పాస్‌వర్డ్ కనీసం 8 అక్షరాలు ఉండాలి', password_reset_success: 'పాస్‌వర్డ్ విజయవంతంగా రీసెట్ చేయబడింది!',
    super_admin_portal: 'సూపర్ అడ్మిన్ పోర్టల్', login_as_super_admin: 'సూపర్ అడ్మిన్‌గా లాగిన్ చేయండి',
    super_admin_default_creds: '🔒 డిఫాల్ట్: ఫోన్=9999999999, పాస్‌వర్డ్=Super@123',
    india_agri_market: "భారతదేశ వ్యవసాయ మార్కెట్‌ప్లేస్", buy_seeds_hero: "విత్తనాలు కొనండి", sell_grains_hero: "ధాన్యాలు అమ్మండి",
    grow_better: "మంచిగా పండించండి", hero_desc_full: "లైవ్ మార్కెట్ ధరలను బ్రౌజ్ చేయండి, ప్రీమియం విత్తనాలను అన్వేషించండి మరియు ధృవీకరించబడిన గిడ్డంగులతో కనెక్ట్ అవ్వండి. ఉచితంగా నమోదు చేసుకోండి.",
    buy_seeds_btn: "విత్తనాలు కొనండి", sell_grains_btn: "ధాన్యాలు అమ్మండి", hero_badges: "✓ సులభమైన నమోదు  ·  ✓ దాచిన ఛార్జీలు లేవు  ·  ✓ అడ్మిన్ ధృవీకరించబడింది",
    footer_copyright: "© 2026 Sri Siva Sai Seeds. భారతీయ రైతులను శక్తివంతం చేస్తోంది.",
    // Farmer Dashboard
    total_earned: 'విజయమైన ఆదాయం', seed_investment: 'విత్తనాల పెట్టుబడి', upcoming_visits: 'రాబోయే సందర్శనాలు',
    four_month_cycle: '4 నెలల పంట చక్రం', upcoming_farm_visits: 'రాబోయే వ్యవసాయ సందర్శనాలు',
    no_visits_scheduled: 'సందర్శనాలు నిర్ధారించబడలేదు', month_visit: 'నెల {{month}} సందర్శనం', date_tbd: 'తేదీ తర్వాత నిర్ధారిస్తాము',
    recent_crops: 'ఇటీవలి పంటలు', view_all: 'అన్నీ చూడండి', no_crops_registered: 'ఇంకా పంటలు నమోదు కాలేదు',
    sowed: 'నాటినది', recent_transactions: 'ఇటీవలి లెక్కలు', no_transactions_yet: 'ఇంకా లెక్కలు లేవు',
    register_crop: 'పంట నమోదు చేయండి', book_slot: 'స్లాట్ బుక్ చేయండి',
    morning: 'ఉదయం', afternoon: 'మధ్యాహ్నం', evening: 'సాయంత్రం', good_greeting: 'శుభ {{time}}',
    dashboard_manage_desc: 'మీ దస్ప్బోర్డ్ నుండి మీ వ్యవసాయం, పంటలు మరియు లెక్కలను నిర్వహించండి.',
    // Crop Management
    sowing: 'విత్తనం వేయడం', growth: 'వికాసం', maturity: 'పక్వత', harvest: 'కోత', growing: 'పెరుగుతోంది',
    verification_visit: 'ధృవీకరణ సందర్శనం', monitoring: 'పర్యవేక్షణ', progress_visit: 'ప్రగతి సందర్శనం',
    ready_to_sell: 'అమ్మడానికి సిద్ధం', active_growth: 'చురుకుగా పెరుగుతోంది',
    crop_management_desc: 'మీ పంట నమోదులను నిర్వహించండి మరియు వికాస చక్రాలను ట్రాక్ చేయండి',
    no_crops_yet: 'ఇంకా పంటలు నమోదు కాలేదు', register_first_crop: 'ట్రాకింగ్ ప్రారంభించడానికి మీ మొదటి పంటను నమోదు చేయండి',
    farm_visits: 'వ్యవసాయ సందర్శనాలు', fill_crop_details: 'మీ పంట వివరాలు నింపండి',
    farm_visits_auto_scheduled: '📅 నెల 1 (ధృవీకరణ) మరియు నెల 3 (ప్రగతి పరిశీలన) కు వ్యవసాయ సందర్శనాలు స్వయంచాలికంగా షేడ్యూల్ అవుతాయి.',
    registering: 'నమోదు అవుతోంది...', enter_valid_acreage: 'సరైన ఎకరాల సంఖ్యను నమోదు చేయండి',
    crop_registered_success: 'పంట నమోదు అయింది! నెల 1 మరియు 3 కు సందర్శనాలు షేడ్యూల్ అయ్యాయి.',
    acres_placeholder: 'ఎకరాల సంఖ్య (ఉదా. 4.5)',
    // Seed Purchase
    seed_purchase_desc_subtitle: 'అడ్మిన్ ఇన్వెంటరీ నుంచి ప్రీమియం విత్తనాలను బ్రౌజ్ చేసి కొనుగోలు చేయండి',
    browse_seeds: 'విత్తనాలు చూడండి', purchase_history: 'కొనుగోలు చరిత్ర', search_seeds_placeholder: 'పేరు లేదా రకం ద్వారా విత్తనాలు వెతకండి...',
    purchase: 'కొనుగోలు', no_purchases_yet: 'ఇంకా కొనుగోలులు లేవు', order_summary: 'ఆర్డర్ సారాంశం',
    processing: 'ప్రక్రియిస్తున్నాము...', confirm_purchase: 'కొనుగోలు ధృవీకరించండి', enter_valid_quantity: 'సరైన పరిమాణం నమోదు చేయండి',
    max_available: 'గరిష్ట లభ్యం', quantity_kg_placeholder: 'కిలోలలో పరిమాణం',
    // Grain Sales
    grain_sales_desc: 'అమ్మకానికి ధాన్యాలు సమర్పించండి మరియు స్థితిని ట్రాక్ చేయండి', new_sale: 'కొత్త అమ్మకం',
    todays_market_rates: 'నేటి మార్కెట్ ధరలు', my_grain_sales: 'నా ధాన్యం అమ్మకాల అభ్యర్థనలు',
    no_grain_sales_yet: 'ఇంకా ధాన్యం అమ్మకాలు సమర్పించబడలేదు', submit_grain_sale: 'ధాన్యం అమ్మకం సమర్పించండి',
    good_material_counts_desc: 'చెల్లింపుకు మంచి పదార్థం మాత్రమే లెక్కించబడుతుంది',
    link_to_crop: 'పంటకు లింక్ చేయండి (ఐచ్ఛికం)', estimated_payment: 'అంచనా చెల్లింపు',
    wastage_note: 'వ్యర్థం చెల్లింపులో లెక్కించబడదు. అంతిమ మొత్తం అడ్మిన్ ధృవీకరణకు లోబడి ఉంటుంది.',
    submit_sale_request: 'అమ్మకం అభ్యర్థన సమర్పించండి', enter_good_material: 'మంచి పదార్థం పరిమాణం నమోదు చేయండి',
    farmer_portal: 'రైతు పోర్టల్',
    // Booking Slot
    booking_slot_desc: 'గిడ్డంగులకు ధాన్యపు బట్వాడాలను షేడ్యూల్ చేయండి', my_booking_slots: 'నా బుకింగ్ స్లాట్లు',
    no_slots_booked_yet: 'ఇంకా స్లాట్లు బుక్ చేయబడలేదు', schedule_grain_delivery: 'గిడ్డంగికి ధాన్యపు బట్వాడాను షేడ్యూల్ చేయండి',
    booking: 'బుకింగ్ అవుతోంది...', confirm_booking: 'బుకింగ్ నిర్ధారించండి', warehouse: 'గిడ్డంగి', delivery_address: 'బట్వాడా చిరునామా',
    // Transaction History
    transaction_history_desc: 'మీ చెల్లింపులు మరియు రసీదులన్నీ చూడండి', export_csv: 'CSV ఎగుమతి చేయండి',
    total_spent: 'మొత్తం ఖర్చు', total_transactions: 'మొత్తం లెక్కలు', search_tx_placeholder: 'వివరణ, UPI ID లేదా ఇన్‌వాయిస్ ద్వారా వెతకండి...',
    no_transactions_found: 'లెక్కలు ఏమీ కనుగొనబడలేదు', type: 'రకం', description: 'వివరణ',
    // Profile
    profile_settings_desc: 'మీ వ్యక్తిగత మరియు బ్యాంకింగ్ సమాచారాన్ని నిర్వహించండి', personal_info: 'వ్యక్తిగత సమాచారం',
    edit: 'సవరించండి', farm_location: 'వ్యవసాయ స్థానం', saving: 'సేవ్ అవుతోంది...', save_changes: 'మార్పులను సేవ్ చేయండి',
    agri_details: 'వ్యవసాయ వివరాలు', land_size: 'భూమి పరిమాణం (ఎకరాలు)', soil_type: 'నేల రకం',
    irrigation_type: 'నీటిపారుదల రకం', primary_crop: 'ప్రధాన పంట', secondary_crop: 'ద్వితీయ పంట (ఐచ్ఛికం)',
    required_documents: 'అవసరమైన పత్రాలు', aadhaar_card: 'ఆధార్ కార్డ్ కాపీ', bank_passbook: 'బ్యాంక్ పాస్‌బుక్ కాపీ',
    land_ownership: 'భూ యాజమాన్య రుజువు',
    // SuperAdmin Dashboard
    system_overview: 'సిస్టమ్ అవలోకనం', platform_stats_desc: 'ప్లాట్‌ఫారమ్-వ్యాప్త గణాంకాలు మరియు కార్యాచరణ',
    system_status: 'సిస్టమ్ స్థితి', all_systems_operational: 'అన్ని సిస్టమ్స్ పనిచేస్తున్నాయి',
    total_farmers: 'మొత్తం రైతులు', system_managers: 'సిస్టమ్ మేనేజర్లు', farm_visits_recorded: 'రికార్డ్ చేయబడిన వ్యవసాయ సందర్శనాలు',
    active_warehouses: 'క్రియాశీల గిడ్డంగులు', weekly_activity: 'వారపు ప్లాట్‌ఫారమ్ కార్యాచరణ', recent_logins: 'ఇటీవలి అడ్మిన్ లాగిన్‌లు',
    active_warehouses: 'క్రియాశీల గిడ్డంగులు', weekly_activity: 'వారపు ప్లాట్‌ఫారమ్ కార్యాచరణ', recent_logins: 'ఇటీవలి అడ్మిన్ లాగిన్‌లు',
    manager_user: 'మేనేజర్ యూజర్', just_now: 'ఇప్పుడే', hours_ago: 'గంటల క్రితం', daily_logins: 'రోజువారీ లాగిన్‌లు', new_farmers: 'కొత్త రైతులు',
    // Admin Dashboard
    system_overview_desc: 'సిస్టమ్ అవలోకనం మరియు విశ్లేషణలు', active_farmers: 'క్రియాశీల రైతులు', active_crop_cycles: 'క్రియాశీల పంట చక్రాలు',
    procurement_mtd: 'సేకరణ (MTD)', warehouse_inv: 'గిడ్డంగి ఇన్వెంటరీ', total_revenue_mtd: 'మొత్తం ఆదాయం (MTD)',
    net_profit_mtd: 'నికర లాభం (MTD)', pending_payments: 'పెండింగ్ చెల్లింపులు', visitors_today: 'నేటి సందర్శకులు',
    monthly_revenue: 'నెలవారీ ఆదాయం', warehouse_capacity: 'గిడ్డంగి సామర్థ్యం', used: 'ఉపయోగించినది',
    action_required: 'చర్య అవసరం', pending_registration: 'నమోదు పెండింగ్‌లో ఉంది', farmers_waiting_approval: 'ఆమోదం కోసం ఎదురుచూస్తున్న రైతులు',
    review: 'సమీక్షించండి', pay_farmer: 'రైతుకు చెల్లించండి', paid: 'చెల్లించబడింది', saving: 'సేవ్ అవుతోంది...', booking_details: 'బుకింగ్ వివరాలు', booking_id: 'బుకింగ్ ఐడి',
    mr_grade_available: "అందుబాటులో ఉన్న గ్రేడ్‌లు", available_status: "అందుబాటులో ఉంది", account_details: "ఖాతా వివరాలు", cache_management: "క్యాషే నిర్వహణ", billing_invoices: "బిల్లింగ్ & ఇన్‌వాయిస్‌లు", grain_procurement: "ధాన్యం సేకరణ", qtl: "క్వింటాళ్ళు",
    rice: "వరి", wheat: "గోధుమ", maize: "మొక్కజొన్న", cotton: "పత్తి", sugarcane: "చెరకు", groundnut: "వేరుశనగ", bajra: "సజ్జలు", red_gram: "కందిపప్పు",
    active: 'క్రియాశీలం', dispatch_success: '{{quantity}}kg {{grain}} విజయవంతంగా {{name}}కి పంపబడింది',
    logs_downloaded: 'లాగ్‌లు విజయవంతంగా డౌన్‌లోడ్ అయ్యాయి',
    all: 'అన్ని', credit: 'క్రెడిట్', debit: 'డెబిట్',
    export_report: 'నివేదిక ఎగుమతి చేయండి', search_logs_placeholder: 'చర్య లేదా రైతు ద్వారా వెతకండి...', timestamp: 'సమయం', manager: 'మేనేజర్', action: 'చర్య', entity_affected: 'రైతు / సంస్థ', details: 'వివరాలు', no_logs_found: 'లాగ్‌లు ఏవీ కనుగొనబడలేదు',
    mr_live_prices: "లైవ్ ధరలు", mr_hero_title: "నేడు మార్కెట్ రేట్లు", mr_hero_desc: "గ్రేడ్ వారీగా రీల్-టైమ్ ధాన్యం ధరలు - అడ్మిన్ అప్డేట్ చేసినవి. మిగతా పంటలు మరియు గ్రేడ్లు కింద చూడండి.", mr_grain_price_index: "ధాన్యం ధర సూచీకాంకం", mr_filter_desc: "అన్ని గ్రేడ్ల కి.g. ధరలు చూడటానికి పంట రకం ఎంచుకోండి", mr_sell_your_grains: "ధాన్యం అమ్మండి", mr_all_crops: "అన్ని పంటలు", mr_price_per_kg: "కేజీకి ధర", mr_grade_premium: "ప్రీమియం", mr_grade_standard: "స్టాండర్డ్", mr_grade_basic: "బేసిక్", mr_sell_btn: "అమ్మండి", mr_no_rates: "అడ్మిన్ సెట్ చేసిన తర్వాత మార్కెట్ రేట్లు ఇక్కడ కనిపిస్తాయి", mr_cta_title: "మీ ధాన్యం అమ్మడానికి సిద్ధంగా ఉన్నారా?", mr_cta_desc: "రైతుగా నమోదు చేసుకోండి మరియు అత్యుత్తమ ధరలకు మీ పంటను సమర్పించండి.", mr_get_started: "ప్రారంభించండి", sc_premium_quality: "ప్రీమియం నాణ్యమైన విత్తనాలు", sc_hero_title: "విత్తనాల కేటలాగ్", sc_hero_desc: "ప్రతి పంట రకం కోసం అడ్మిన్-ధృవీకరించబడ్డ ప్రీమియం విత్తనాల రకాలు. నమ్మకంగా కొనండి.", sc_search_placeholder: "పేరు లేదా రకం ద్వారా విత్తనాలు వెతుకండి...", sc_browse_buy: "విత్తనాలు చూసి కొనండి", sc_verified: "ధృవీకరించబడ్డది", sc_in_stock: "నిల్వలో ఉంది", sc_buy_now: "ఇప్పుడే కొనండి", sc_kg_left: "కేజీలు మిగిలాయి", sc_no_seeds: "విత్తనాల కేటలాగ్ ఇక్కడ కనిపిస్తుంది", sc_no_match: "మీ వెతుకుకు సరిపోయే విత్తనాలు లేవు", sc_cta_title: "ప్రీమియం విత్తనాలు కొనడానికి సిద్ధంగా ఉన్నారా?", sc_cta_desc: "రైతుగా నమోదు చేసుకోండి మరియు విత్తనాలు ఆర్డర్ ఇవ్వండి.", sc_get_started: "ప్రారంభించండి", hiw_simple_process: "సులభమైన ప్రక్రియ", hiw_hero_title: "Sri Siva Sai Seeds ఎలా పని చేస్తుంది", hiw_hero_desc: "రైతులను న్యాయమైన మార్కెట్లు మరియు ప్రీమియం సరఫరాలతో కలుపుతుంది.", hiw_step1_title: "నమోదు చేసి ఆమోదం పొందండి", hiw_step1_desc: "Register as a new farmer by providing personal and farming details. Once saved, become part of the verified network and can access all platform services.", hiw_step2_title: "చూసి నిర్ణయించుకోండి", hiw_step2_desc: "ఆమోదించిన తర్వాత, పూర్ణ డ్యాష్బోర్డ్ అక్సెస్ చేయండి. లైవ్ మార్కెట్ ధరలు చెక్ చేయండి.", hiw_step3_title: "కొనండి లేదా అమ్మండి", hiw_step3_desc: "ప్లాట్ఫార్మ్ ద్వారా నేరుగా విత్తనాలు కొనండి లేదా మీ ధాన్యం సమర్పించండి. అన్ని లేన్దేనాలు సురక్షితంగా ఉన్నాయి.", hiw_start_journey: "మీ యాత్ర ప్రారంభించండి", feat_platform: "సమగ్ర ప్లాట్ఫార్మ్", feat_hero_title: "రైతుకు అవసరమైన అన్నిటి", feat_hero_desc: "విత్తనం నుండి అమ్మకం వరకు వ్యవసాయ కార్యక్రమాలను సువ్యవస్థితం చేసే శక్తివంతమైన సాధనాలు.", feat_cta_title: "ఈ సువిధాలను ఉపయోగించికోవడానికి సిద్ధంగా ఉన్నారా?", feat_cta_desc: "నేడే Sri Siva Sai Seeds సముదాయంలో చేరండి.", feat_create_account: "ఉచిత ఖాతా సృష్టించండి",
    feat1_title: "లైవ్ మార్కెట్ రేట్లు", feat1_desc: "అన్ని గ్రేడ్లకు (A, B, C) జిల్లా నిర్వాహకులు అప్‌డేట్ చేసిన రీల్-టైమ్ పంట ధరలు. అమ్మకం ముందు సరిపోయిన నిర్ణయాలు తీసుకోండి.",
    feat2_title: "విత్తనాల కొనుగోలు", feat2_desc: "ధృవీకరించబడిన సప్లయర్ల నుండి ప్రీమియం విత్తనాలను ఆన్‌లైన్‌లో ఆర్డర్ చేయండి. UPI ద్వారా సురక్షితంగా చెల్లించండి.",
    feat3_title: "పంట ట్రాకింగ్", feat3_desc: "మీ పంటలను నమోదు చేయండి మరియు వాటి 4-నెలల పెరుగుదల చక్రాన్ని ట్రాక్ చేయండి.",
    feat4_title: "గిడ్డంగి బుకింగ్", feat4_desc: "సమీప గిడ్డంగులలో బట్వాడా స్లాట్‌లను బుక్ చేయండి. వేచి ఉండకుండా మీ ధాన్యం భద్రంగా నిల్వ చేసుకోండి.",
    feat5_title: "సురక్షిత చెల్లింపులు", feat5_desc: "అన్ని లావాదేవీలు అడ్మిన్ ద్వారా ధృవీకరించబడతాయి. పూర్తి పారదర్శకతతో సురక్షిత UPI చెల్లింపులు ఆనందించండి.",
    feat6_title: "24/7 అందుబాటు", feat6_desc: "మీ వ్యవసాయ నిర్వహణకు సమయం లేదు. ఎప్పుడైనా, ఎక్కడైనా ధరలు చెక్ చేయండి మరియు పంటలను నిర్వహించండి.",
    revenue_by_month: 'నెలవారీ ఆదాయం',
    active_crop_distribution: 'సక్రియ పంటల పంపిణీ',
    farmer_registration_data: 'రైతు నమోదు సమాచారం',
    farmer_registration_data_desc: 'నమోదిత రైతుల వివరాలు',
    transaction_ledger: 'లావాదేవీల లెడ్జర్',
    transaction_ledger_desc: 'లావాదేవీల పూర్తి చరిత్ర',
    warehouse_inventory_logs: 'గిడ్డంగి నిల్వల లాగ్‌లు',
    warehouse_inventory_logs_desc: 'గిడ్డంగి నిల్వల కోసం లాగ్‌లు',
    super_admin_portal: 'సూపర్ అడ్మిన్ పోర్టల్',
    event_logs: 'ఈవెంట్ లాగ్‌లు',
    event_logs_desc: 'మేనేజర్లు చేసిన అన్ని చర్యలు చూడండి',
    account_information: 'ఖాతా సమాచారం',
    change_password: 'పాస్‌వర్డ్ మార్చండి',
    use_strong_password: 'అక్షరాలు, సంఖ్యలు, చిహ్నాలతో కూడిన బలమైన పాస్‌వర్డ్‌ని ఉపయోగించండి.',
    current_password: 'ప్రస్తుత పాస్‌వర్డ్',
    enter_current_password: 'మీ ప్రస్తుत పాస్‌వర్డ్ నమోదు చేయండి',
    new_password: 'కొత్త పాస్‌వర్డ్',
    at_least_8_chars: 'కనీసం 8 అక్షరాలు',
    one_uppercase_letter: 'ఒక పెద్ద అక్షరం',
    one_number: 'ఒక సంఖ్య',
    one_special_char: 'ఒక ప్రత్యేక చిహ్నం',
    download_report: 'నివేదిక డౌన్‌లోడ్ చేయండి',
    filters: 'వడపోతలు',
    clear_all: 'అన్నీ క్లియర్ చేయి',
    price_range: 'ధర పరిధి',
    availability: 'లభ్యత',
    delivered_to_warehouse: 'గిడ్డంగికి డెలివరీ చేయబడింది',
    inspection_completed: 'తనిఖీ పూర్తయింది',
  }
};

const hi = {
  translation: {
    app_name: 'श्री शिव साई सीड्स',
    loading: 'लोड हो रहा है...', save: 'सहेजें', cancel: 'रद्द करें', confirm: 'पुष्टि करें',
    delete: 'हटाएं', edit: 'संपादित करें', view: 'देखें', approve: 'अनुमोदित करें', reject: 'अस्वीकार करें',
    submit: 'जमा करें', search: 'खोजें', filter: 'फ़िल्टर', download: 'डाउनलोड',
    yes: 'हाँ', no: 'नहीं', ok: 'ठीक है', close: 'बंद करें', back: 'वापस',
    success: 'सफलता', error: 'त्रुटि', warning: 'चेतावनी', info: 'जानकारी',
    status: 'स्थिति', date: 'तारीख', amount: 'राशि', quantity: 'मात्रा',
    actions: 'क्रियाएं', details: 'विवरण', name: 'नाम', phone: 'फ़ोन',
    email: 'ईमेल', address: 'पता', password: 'पासवर्ड',
    login: 'लॉगिन', logout: 'लॉग आउट', register: 'पंजीकरण',
    farmer_login: 'किसान लॉगिन', admin_login: 'प्रबंधक लॉगिन', super_admin_login: 'सुपर एडमिन लॉगिन',
    mobile_number: 'मोबाइल नंबर', send_otp: 'OTP भेजें', verify_otp: 'OTP सत्यापित करें',
    forgot_password: 'पासवर्ड भूल गए', remember_me: 'मुझे याद रखें',
    otp_sent: 'आपके मोबाइल पर OTP भेजा गया',
    registration_pending: 'पंजीकरण जमा किया गया। व्यवस्थापक अनुमोदन की प्रतीक्षा है।',
    welcome_back: 'वापस स्वागत है!', sign_in_desc: 'अपने Sri Siva Sai Seeds खाते में साइन इन करें',
    sign_in: 'साइन इन',

    // Nav / Landing
    market_rates_nav: 'बाजार दरें',
    seeds_catalog_nav: 'बीज कैटलॉग',
    how_it_works_nav: 'यह कैसे काम करता है',
    features_nav: 'विशेषताएं',
    go_to_dashboard: 'डैशबोर्ड पर जाएं',
    hero_title: 'आधुनिक खेती, स्मार्ट बाजार',
    hero_subtitle: 'Sri Siva Sai Seeds किसानों को सत्यापित बीज, लाइव बाजार मूल्य और पारदर्शी अनाज व्यापार से जोड़ता है।',
    get_started: 'शुरू करें',
    view_market_rates: 'बाजार दरें देखें',
    trusted_by: 'तेलंगाना भर के किसानों द्वारा विश्वसनीय',
    live_market_prices: 'लाइव बाजार मूल्य',
    live_market_desc: 'एडमिन द्वारा अपडेट की गई अनाज कीमतें। बेचने से पहले जानें कि आप कितना कमाएंगे।',
    explore_seeds: 'बीज कैटलॉग देखें',
    available_seeds: 'उपलब्ध बीज',
    seeds_desc: 'गुणवत्ता आश्वासन के साथ प्रमाणित बीज खरीदें।',
    browse_catalog: 'कैटलॉग देखें',
    how_it_works: 'यह कैसे काम करता है',
    how_it_works_desc: 'Sri Siva Sai Seeds के साथ शुरू करने के लिए तीन आसान चरण।',
    register_step: 'पंजीकरण करें और अनुमोदन प्राप्त करें',
    register_step_desc: '24 घंटों में किसान खाता बनाएं और व्यवस्थापक द्वारा सत्यापित हों।',
    browse_step: 'देखें और निर्णय लें',
    browse_step_desc: 'लाइव बाजार मूल्य जांचें, बीज कैटलॉग देखें।',
    trade_step: 'विश्वास के साथ खरीदें और बेचें',
    trade_step_desc: 'बीज खरीदें या अनाज बिक्री जमा करें।',
    why_agriflow: 'Sri Siva Sai Seeds क्यों?',
    fair_prices: 'उचित मूल्य', fair_prices_desc: 'सत्यापित प्रशासकों द्वारा प्रतिदिन अपडेट की जाने वाली पारदर्शी कीमतें।',
    verified_seeds: 'सत्यापित बीज', verified_seeds_desc: 'सभी बीज गुणवत्ता-जांचे और प्रमाणित हैं।',
    fast_payments: 'त्वरित भुगतान', fast_payments_desc: 'आपकी अनाज बिक्री अनुमोदित होने के बाद जल्दी भुगतान पाएं।',
    expert_support: 'विशेषज्ञ सहायता', expert_support_desc: 'हमारी टीम आपके खेत में आती है और हर कदम में मार्गदर्शन करती है।',
    start_journey: 'अपनी यात्रा शुरू करें',
    register_free: 'मुफ्त पंजीकरण',
    already_farmer: 'पहले से किसान हैं?',
    need_credentials: 'Sri Siva Sai Seeds में नए हैं?',
    need_credentials_desc: 'अपना फार्म पंजीकृत करने और अपने लॉगिन क्रेडेंशियल प्राप्त करने के लिए हमारी टीम से संपर्क करें।',
    call_us: 'कॉल करें',
    visit_us: 'हमसे मिलें',
    office_address: 'श्री शिव साई सीड्स, कुरनूल, आंध्र प्रदेश, 518004',

    dashboard: 'डैशबोर्ड', farm_overview: 'फार्म अवलोकन',
    crops_cycles: 'फसलें और चक्र', booking_slot: 'बुकिंग स्लॉट',
    transaction_history: 'लेनदेन इतिहास', seed_purchase: 'बीज खरीद',
    grain_sales: 'अनाज बिक्री', profile_settings: 'प्रोफाइल / सेटिंग्स',
    farmers: 'किसान', warehouse: 'गोदाम प्रबंधन',
    reports: 'रिपोर्ट और विश्लेषण', seeds_inventory: 'बीज सूची',
    farm_visits: 'खेत यात्राएं', market_rates: 'बाजार दरें',
    manage_admins: 'प्रबंधक', audit_logs: 'ऑडिट लॉग', settings: 'सेटिंग्स',
    total_farmers: 'कुल किसान', active_fields: 'सक्रिय खेत',
    total_revenue: 'कुल राजस्व', warehouse_capacity: 'गोदाम क्षमता',
    active_farmers: 'सक्रिय किसान', pending_approvals: 'लंबित अनुमोदन',
    recent_transactions: 'हाल के लेनदेन', monthly_revenue: 'मासिक राजस्व',
    quick_actions: 'त्वरित क्रियाएं', add_farmer: 'किसान जोड़ें',
    set_market_rate: 'बाजार दर सेट करें', view_reports: 'रिपोर्ट देखें',
    manage_warehouse: 'गोदाम प्रबंधित करें',
    farmers_directory: 'किसान निर्देशिका',
    farmer_management: 'किसान प्रबंधन',
    registered_farmers: 'पंजीकृत किसान',
    pending_verification: 'लंबित सत्यापन',
    export_csv: 'CSV निर्यात',
    all_statuses: 'सभी स्थितियां',
    no_farmers_found: 'कोई किसान नहीं मिला',
    farmer_details: 'किसान विवरण',
    bank_account: 'बैंक खाता',
    not_provided: 'प्रदान नहीं किया',
    add_seed: 'बीज जोड़ें', update_stock: 'स्टॉक अपडेट करें',
    price_per_kg: 'प्रति किग्रा मूल्य', available_stock: 'उपलब्ध स्टॉक',
    in_stock: 'स्टॉक में', out_of_stock: 'स्टॉक नहीं',
    stock_kg: 'स्टॉक (किग्रा)', is_active: 'सक्रिय',
    crop_type: 'फसल प्रकार', acres: 'एकड़', sowing_date: 'बुवाई तिथि',
    add_crop: 'फसल जोड़ें', register_crop: 'फसल पंजीकृत करें',
    seed_name: 'बीज का नाम', variety: 'किस्म',
    grain_type: 'अनाज प्रकार', grade: 'ग्रेड', grade_a: 'ग्रेड A',
    grade_b: 'ग्रेड B', grade_c: 'ग्रेड C', raw_material: 'कच्चा माल (किग्रा)',
    wastage: 'बर्बादी (किग्रा)', good_material: 'अच्छा माल (किग्रा)',
    booking_date: 'बुकिंग तिथि', delivery_address: 'डिलीवरी पता',
    set_rate: 'दर सेट करें', price_per_kg_label: 'प्रति किग्रा मूल्य (₹)',
    effective_date: 'प्रभावी तिथि', crop_name: 'फसल का नाम',
    current_rates: 'वर्तमान दरें',
    warehouse_name: 'गोदाम का नाम', location: 'स्थान',
    total_capacity: 'कुल क्षमता', used_capacity: 'प्रयुक्त क्षमता',
    available: 'उपलब्ध', add_warehouse: 'गोदाम जोड़ें',
    bank_details: 'बैंक विवरण', bank_name: 'बैंक का नाम',
    account_number: 'खाता संख्या', ifsc_code: 'IFSC कोड',
    change_request_pending: 'परिवर्तन अनुरोध व्यवस्थापक अनुमोदन के लिए लंबित है',
    request_bank_change: 'बैंक विवरण परिवर्तन अनुरोध',
    acres_of_land: 'भूमि का एकड़', crop_address: 'फसल/खेत स्थान',
    quantity_kg: 'मात्रा (किग्रा)', total_amount: 'कुल राशि',
    purchase_seeds: 'बीज खरीदें',
    book_slot: 'स्लॉट बुक करें',
    pending: 'लंबित', active: 'सक्रिय', approved: 'अनुमोदित',
    rejected: 'अस्वीकृत', completed: 'पूर्ण', confirmed: 'पुष्टि की',
    cancelled: 'रद्द', paid: 'भुगतान किया', failed_status: 'विफल',
    language: 'भाषा', english: 'English', telugu: 'తెలుగు', hindi: 'हिंदी',
    notifications: 'सूचनाएं', no_notifications: 'कोई नई सूचना नहीं',
    mark_all_read: 'सभी को पढ़ा हुआ चिह्नित करें',
    chatbot: 'बाजार सहायक', ask_market: 'बाजार मूल्यों के बारे में पूछें...',
    price_forecast: 'मूल्य पूर्वानुमान',
    global_farmer_directory: 'वैश्विक किसान निर्देशिका',
    read_only_view: 'सभी पंजीकृत किसानों का केवल-पढ़ने योग्य दृश्य',
    manage_admins_desc: 'प्रबंधक खाते बनाएं और प्रबंधित करें',
    create_admin: 'व्यवस्थापक बनाएं',
    system_audit_logs: 'सिस्टम ऑडिट लॉग',
    audit_logs_desc: 'व्यवस्थापकों और प्रबंधकों द्वारा किए गए सभी महत्वपूर्ण कार्यों को ट्रैक करें',
    operational_portal: 'परिचालन पोर्टल',
    
    // Form & Auth Additions
    full_name: 'पूरा नाम *', your_full_name: 'आपका पूरा नाम',
    email_optional: 'ईमेल (वैकल्पिक)', your_email: 'your@email.com',
    min_8_chars: 'न्यूनतम 8 वर्ण', confirm_password: 'पासवर्ड की पुष्टि करें *', repeat_password: 'पासवर्ड दोहराएं',
    enter_6_digit_otp: '6 अंकों का OTP दर्ज करें', resend_otp_in: 'OTP फिर से भेजें',
    didnt_receive_code: "क्या कोड नहीं मिला?", resend_otp: 'OTP फिर से भेजें',
    home_address_placeholder: 'आपका घर/डाक का पता', eg_5_5: 'जैसे 5.5',
    crop_address_placeholder: 'आपके खेत का गांव/सर्वे नंबर/जीपीएस स्थान',
    registration_review_msg: '⏳ आपकी पंजीकरण सक्रियण से पहले एक व्यवस्थापक द्वारा समीक्षा की जाएगी। स्वीकृत होने के बाद आपको एक सूचना प्राप्त होगी।',
    submitting: 'जमा कर रहे हैं...', submit_registration: 'पंजीकरण जमा करें',
    already_have_account: 'क्या पहले से कोई खाता है?', login_here: 'यहां लॉगिन करें',
    create_farmer_account: 'किसान खाता बनाएं', join_agriflow: 'Sri Siva Sai Seeds से जुड़ें और अपने खेत का प्रबंधन शुरू करें',
    personal_info: 'व्यक्तिगत जानकारी', verify_otp_step: 'OTP सत्यापित करें', farm_details: 'खेत विवरण',
    please_fill_all_fields: 'कृपया सभी फ़ील्ड भरें', login_failed: 'लॉगिन विफल रहा',
    agricultural_partner: 'आपका कृषि भागीदार', crop_tracking: 'फसल ट्रैकिंग',
    crop_tracking_desc: '4 महीने के चक्र की निगरानी', grain_sales_title: 'अनाज की बिक्री',
    grain_sales_desc: 'ग्रेड आधारित मूल्य निर्धारण', seed_purchase_title: 'बीज खरीद',
    seed_purchase_desc: 'प्रीमियम बीज की किस्में', market_rates_title: 'बाजार दरें',
    market_rates_desc: 'रीयल-टाइम मूल्य अद्यतन', back_to_home: 'होम पर वापस जाएं',
    mobile_placeholder: '10 अंकों का मोबाइल नंबर', password_placeholder: 'पासवर्ड दर्ज करें',
    signing_in: 'साइन इन कर रहे हैं...', new_farmer: 'नए किसान?',
    demo_farmer_msg: '🌾 डेमो किसान: एक नया खाता पंजीकृत करें या अपने व्यवस्थापक से क्रेडेंशियल मांगें।',
    passwords_do_not_match: 'पासवर्ड मेल नहीं खाते', enter_valid_phone: 'मान्य 10 अंकों का फोन नंबर दर्ज करें',
    invalid_otp: 'अमान्य OTP', fill_all_details: 'सभी खेत विवरण भरें',
    manager_portal: 'प्रबंधक पोर्टल', agriflow_erp_admin: 'Sri Siva Sai Seeds प्रशासन',
    login_as_manager: 'प्रबंधक के रूप में लॉगिन करें', manager_default_creds: '🔒 डिफ़ॉल्ट: फोन=8888888888, पासवर्ड=Manager@123',
    reset_password: 'पासवर्ड रीसेट करें', recover_access_desc: 'अपने Sri Siva Sai Seeds खाते तक पहुंच पुनः प्राप्त करें',
    enter_mobile_number: 'अपना मोबाइल नंबर दर्ज करें', send_reset_otp: 'रीसेट OTP भेजें',
    enter_otp_sent_to: 'पर भेजा गया OTP दर्ज करें', set_new_password: 'नया पासवर्ड सेट करें',
    new_password_placeholder: 'नया पासवर्ड (न्यूनतम 8 वर्ण)', confirm_new_password_placeholder: 'नया पासवर्ड की पुष्टि करें',
    resetting: 'रीसेट कर रहे हैं...', back_to_login: 'लॉगिन पर वापस जाएं', phone_not_registered: 'फोन पंजीकृत नहीं है',
    password_min_8: 'पासवर्ड कम से कम 8 वर्णों का होना चाहिए', password_reset_success: 'पासवर्ड सफलतापूर्वक रीसेट किया गया!',
    super_admin_portal: 'सुपर एडमिन पोर्टल', login_as_super_admin: 'सुपर एडमिन के रूप में लॉगिन करें',
    super_admin_default_creds: '🔒 डिफ़ॉल्ट: फोन=9999999999, पासवर्ड=Super@123',
    india_agri_market: "भारत का कृषि मार्केटप्लेस", buy_seeds_hero: "बीज खरीदें", sell_grains_hero: "अनाज बेचें",
    grow_better: "बेहतर उगाएं", hero_desc_full: "लाइव बाजार दरों को ब्राउज़ करें, प्रीमियम बीज किस्मों का पता लगाएं, और सत्यापित गोदामों से जुड़ें। मुफ्त में पंजीकरण करें।",
    buy_seeds_btn: "बीज खरीदें", sell_grains_btn: "अनाज बेचें", hero_badges: "✓ आसान पंजीकरण  ·  ✓ कोई छिपा शुल्क नहीं  ·  ✓ व्यवस्थापक सत्यापित",
    footer_copyright: "© 2026 Sri Siva Sai Seeds। भारतीय किसानों को सशक्त बनाना।",
    // Farmer Dashboard
    total_earned: 'कुल कमाई', seed_investment: 'बीज निवेश', upcoming_visits: 'आने वाले दौरे',
    four_month_cycle: '4 महीने का फसल चक्र', upcoming_farm_visits: 'आने वाले खेत दौरे',
    no_visits_scheduled: 'कोई दौरा निर्धारित नहीं', month_visit: 'महीना {{month}} दौरा', date_tbd: 'तारीख बाद में',
    recent_crops: 'हालिया फसलें', view_all: 'सभी देखें', no_crops_registered: 'अभी तक कोई फसल दर्ज नहीं',
    sowed: 'बोया गया', recent_transactions: 'हालिया लेनदेन', no_transactions_yet: 'अभी तक कोई लेनदेन नहीं',
    register_crop: 'फसल दर्ज करें', book_slot: 'स्लॉट बुक करें',
    morning: 'सुबह', afternoon: 'दोपहर', evening: 'शाम', good_greeting: 'शुभ {{time}}',
    dashboard_manage_desc: 'अपने डैशबोर्ड से अपना खेत, फसलें और लेनदेन प्रबंधित करें।',
    // Crop Management
    sowing: 'बुवाई', growth: 'विकास', maturity: 'परिपक्वता', harvest: 'फसल कण', growing: 'उग रही है',
    verification_visit: 'सत्यापन दौरा', monitoring: 'निगरानी', progress_visit: 'प्रगति दौरा',
    ready_to_sell: 'बेचने के लिए तैयार', active_growth: 'सक्रिय विकास',
    crop_management_desc: 'अपने फसल पंजीकरणों को प्रबंधित करें और विकास चक्रों को ट्रैक करें',
    no_crops_yet: 'अभी तक कोई फसल दर्ज नहीं', register_first_crop: 'ट्रैकिंग शुरू करने के लिए अपनी पहली फसल दर्ज करें',
    farm_visits: 'खेत दौरे', fill_crop_details: 'अपने फसल का विवरण भरें',
    farm_visits_auto_scheduled: '📅 दौरे महीना 1 (सत्यापन) और महीना 3 (प्रगति जांच) के लिए स्वचालित रूप से निर्धारित होंगे।',
    registering: 'दर्ज हो रहा है...', enter_valid_acreage: 'सही एकड़ संख्या दर्ज करें',
    crop_registered_success: 'फसल दर्ज हुई! महीना 1 और 3 के लिए दौरे निर्धारित हुए।',
    acres_placeholder: 'एकड़़ की संख्या (जैसे 4.5)',
    // Seed Purchase
    seed_purchase_desc_subtitle: 'अडमिन इन्वेंटरी से प्रीमियम बीज ब्राउज़ करें और खरीदें',
    browse_seeds: 'बीज देखें', purchase_history: 'खरीद इतिहास', search_seeds_placeholder: 'नाम या किस्म से बीज खोजें...',
    purchase: 'खरीदें', no_purchases_yet: 'अभी तक कोई खरीद नहीं', order_summary: 'ऑर्डर सारांश',
    processing: 'प्रक्रिया हो रही है...', confirm_purchase: 'खरीद की पुष्टि करें', enter_valid_quantity: 'सही मात्रा दर्ज करें',
    max_available: 'अधिकतम उपलब्ध', quantity_kg_placeholder: 'किलोग्राम में मात्रा',
    // Grain Sales
    grain_sales_desc: 'बिक्री के लिए अनाज जमा करें और स्वीकृति स्थिति ट्रैक करें', new_sale: 'नई बिक्री',
    todays_market_rates: 'आज की बाजार दरें', my_grain_sales: 'मेरे अनाज बिक्री अनुरोध',
    no_grain_sales_yet: 'अभी तक कोई अनाज बिक्री जमा नहीं की गई', submit_grain_sale: 'अनाज बिक्री जमा करें',
    good_material_counts_desc: 'भुगतान में केवल अच्छा माल गिना जाता है',
    link_to_crop: 'फसल से जोड़ें (वैकल्पिक)', estimated_payment: 'अनुमानित भुगतान',
    wastage_note: 'अपशिष्ट भुगतान में नहीं गिना जाता। अंतिम राशि व्यवस्थापक सत्यापन के अधीन है।',
    submit_sale_request: 'बिक्री अनुरोध जमा करें', enter_good_material: 'अच्छे माल की मात्रा दर्ज करें',
    farmer_portal: 'किसान पोर्टल',
    // Booking Slot
    booking_slot_desc: 'गोदामों में अनाज वितरण का समय निर्धारित करें', my_booking_slots: 'मेरे बुकिंग स्लॉट',
    no_slots_booked_yet: 'अभी तक कोई स्लॉट बुक नहीं किया गया', schedule_grain_delivery: 'गोदाम में अनाज वितरण का समय निर्धारित करें',
    booking: 'बुकिंग हो रही है...', confirm_booking: 'बुकिंग की पुष्टि करें', warehouse: 'गोदाम', delivery_address: 'वितरण पता',
    // Transaction History
    transaction_history_desc: 'अपने सभी भुगतान और रसीदें देखें', export_csv: 'CSV निर्यात करें',
    total_spent: 'कुल खर्च', total_transactions: 'कुल लेनदेन', search_tx_placeholder: 'विवरण, UPI ID या चालान द्वारा खोजें...',
    no_transactions_found: 'कोई लेनदेन नहीं मिला', type: 'प्रकार', description: 'विवरण',
    // Profile
    profile_settings_desc: 'अपनी व्यक्तिगत और बैंकिंग जानकारी प्रबंधित करें', personal_info: 'व्यक्तिगत जानकारी',
    edit: 'संपादित करें', farm_location: 'खेत का स्थान', saving: 'सहेजा जा रहा है...', save_changes: 'परिवर्तन सहेजें',
    agri_details: 'कृषि विवरण', land_size: 'भूमि का आकार (एकड़)', soil_type: 'मिट्टी का प्रकार',
    irrigation_type: 'सिंचाई का प्रकार', primary_crop: 'मुख्य फसल', secondary_crop: 'द्वितीयक फसल (वैकल्पिक)',
    required_documents: 'आवश्यक दस्तावेज़', aadhaar_card: 'आधार कार्ड की कॉपी', bank_passbook: 'बैंक पासबुक की कॉपी',
    land_ownership: 'भूमि स्वामित्व प्रमाण',
    // SuperAdmin Dashboard
    system_overview: 'सिस्टम अवलोकन', platform_stats_desc: 'प्लेटफ़ॉर्म-व्यापी आँकड़े और गतिविधि',
    system_status: 'सिस्टम स्थिति', all_systems_operational: 'सभी सिस्टम काम कर रहे हैं',
    total_farmers: 'कुल किसान', system_managers: 'सिस्टम प्रबंधक', farm_visits_recorded: 'खेत के दौरे दर्ज किए गए',
    active_warehouses: 'सक्रिय गोदाम', weekly_activity: 'साप्ताहिक प्लेटफ़ॉर्म गतिविधि', recent_logins: 'हाल ही में एडमिन लॉगिन',
    active_warehouses: 'सक्रिय गोदाम', weekly_activity: 'साप्ताहिक प्लेटफ़ॉर्म गतिविधि', recent_logins: 'हाल ही में एडमिन लॉगिन',
    manager_user: 'प्रबंधक उपयोगकर्ता', just_now: 'अभी-अभी', hours_ago: 'घंटे पहले', daily_logins: 'दैनिक लॉगिन', new_farmers: 'नए किसान',
    // Admin Dashboard
    system_overview_desc: 'सिस्टम अवलोकन और एनालिटिक्स', active_farmers: 'सक्रिय किसान', active_crop_cycles: 'सक्रिय फसल चक्र',
    procurement_mtd: 'खरीद (MTD)', warehouse_inv: 'गोदाम इन्वेंटरी', total_revenue_mtd: 'कुल राजस्व (MTD)',
    net_profit_mtd: 'शुद्ध लाभ (MTD)', pending_payments: 'लंबित भुगतान', visitors_today: 'आज के आगंतुक',
    monthly_revenue: 'मासिक राजस्व', warehouse_capacity: 'गोदाम क्षमता', used: 'प्रयुक्त',
    review: 'समीक्षा', pay_farmer: 'किसान को भुगतान करें', paid: 'भुगतान किया गया', saving: 'सहेज रहा है...', booking_details: 'बुकिंग विवरण', booking_id: 'बुकिंग आईडी',
    mr_grade_available: "उपलब्ध ग्रेड", available_status: "उपलब्ध", account_details: "खाता विवरण", cache_management: "कैश प्रबंधन", billing_invoices: "बिलिंग और चालान", grain_procurement: "अनाज खरीद", qtl: "कुंतल",
    rice: "चावल", wheat: "गेहूं", maize: "मक्का", cotton: "कपास", sugarcane: "गन्ना", groundnut: "मूंगफली", bajra: "बाजरा", red_gram: "अरहर",
    review: 'समीक्षा करें', pay_farmer: 'किसान को भुगतान करें', paid: 'भुगतान किया',
    mr_live_prices: "लाइव कीमतें", mr_hero_title: "आज के बाजार भाव", mr_hero_desc: "ग्रेड के अनुसार रियल-टाइम अनाज की कीमतें - एडमिन द्वारा अपडेट। सभी फसलें और ग्रेड नीचे देखें।", mr_grain_price_index: "अनाज मूल्य सूचकांक", mr_filter_desc: "सभी ग्रेड की प्रति किलो दरें देखने के लिए फसल प्रकार चुनें", mr_sell_your_grains: "अनाज बेचें", mr_all_crops: "सभी फसलें", mr_price_per_kg: "प्रति किलो कीमत", mr_grade_premium: "प्रीमियम", mr_grade_standard: "मानक", mr_grade_basic: "सामान्य", mr_sell_btn: "बेचें", mr_no_rates: "एडमिन द्वारा सेट करने के बाद बाजार दरें यहाँ दिखेंगी", mr_cta_title: "अपना अनाज बेचने के लिए तैयार हैं?", mr_cta_desc: "किसान के रूप में पंजीकरण करें और सर्वोत्तम कीमतों पर अपनी फसल जमा करें।", mr_get_started: "शुरू करें", sc_premium_quality: "प्रीमियम गुणवत्ता के बीज", sc_hero_title: "बीज सूची", sc_hero_desc: "हर फसल प्रकार के लिए एडमिन-सत्यापित प्रीमियम बीज किस्में। विश्वास के साथ खरीदें।", sc_search_placeholder: "नाम या किस्म से बीज खोजें...", sc_browse_buy: "बीज देखें और खरीदें", sc_verified: "सत्यापित", sc_in_stock: "स्टॉक में", sc_buy_now: "अभी खरीदें", sc_kg_left: "किलो बचा", sc_no_seeds: "बीज सूची यहाँ दिखेगी", sc_no_match: "आपकी खोज से कोई बीज नहीं मिला", sc_cta_title: "प्रीमियम बीज खरीदने के लिए तैयार हैं?", sc_cta_desc: "किसान के रूप में पंजीकरण करें और बीज का ऑर्डर दें।", sc_get_started: "शुरू करें", hiw_simple_process: "सरल प्रक्रिया", hiw_hero_title: "Sri Siva Sai Seeds कैसे काम करता है", hiw_hero_desc: "एक पारदर्शी, उपयोग में आसान प्लेटफ़ॉर्म जो किसानों को उचित बाजारों और प्रीमियम आपूर्ति से जोड़ता है।", hiw_step1_title: "पंजीकरण करें और स्वीकृत हों", hiw_step1_desc: "Register as a new farmer by providing personal and farming details. Once saved, become part of the verified network and can access all platform services.", hiw_step2_title: "ब्राउज़ करें और निर्णय लें", hiw_step2_desc: "स्वीकृत होने के बाद, पूर्ण डैशबोर्ड एक्सेस करें। लाइव बाजार दरें जांचें, बीज कैटलॉग देखें।", hiw_step3_title: "खरीदें या बेचें", hiw_step3_desc: "प्लेटफ़ॉर्म के माध्यम से सीधे बीज खरीदें या अपनी अनाज फसल जमा करें। सभी लेनदेन सुरक्षित और सत्यापित हैं।", hiw_start_journey: "अपनी यात्रा शुरू करें", feat_platform: "व्यापक प्लेटफ़ॉर्म", feat_hero_title: "किसान की जरूरत की हर चीज", feat_hero_desc: "बीज से बिक्री तक कृषि कार्यों को सुव्यवस्थित करने के लिए शक्तिशाली उपकरण।", feat_cta_title: "इन सुविधाओं का उपयोग करने के लिए तैयार हैं?", feat_cta_desc: "आज ही Sri Siva Sai Seeds समुदाय से जुड़ें।", feat_create_account: "मुफ्त खाता बनाएं",
    feat1_title: "लाइव बाजार दरें", feat1_desc: "सभी ग्रेड (A, B, C) के लिए जिला प्रबंधकों द्वारा अद्यतन रीयल-टाइम फसल की कीमतें। बेचने से पहले सूचित निर्णय लें।",
    feat2_title: "बीज खरीद", feat2_desc: "सत्यापित आपूर्तिकर्ताओं से ऑनलाइन प्रीमियम बीज ऑर्डर करें। UPI के माध्यम से सुरक्षित भुगतान करें।",
    feat3_title: "फसल ट्रैकिंग", feat3_desc: "अपनी फसलों को पंजीकृत करें और उनके 4 महीने के विकास चक्र को ट्रैक करें।",
    feat4_title: "गोदाम बुकिंग", feat4_desc: "पास के गोदामों में डिलीवरी स्लॉट बुक करें। बिना प्रतीक्षा किए अपना अनाज सुरक्षित रूप से स्टोर करें।",
    feat5_title: "सुरक्षित भुगतान", feat5_desc: "सभी लेनदेन प्रशासकों द्वारा सत्यापित होते हैं। पूर्ण पारदर्शिता के साथ सुरक्षित UPI भुगतान का आनंद लें।",
    feat6_title: "24/7 पहुंच", feat6_desc: "आपका कृषि प्रबंधन कभी नहीं सोता। कभी भी, कहीं भी कीमतें जांचें और फसलों का प्रबंधन करें।",
  }
};

i18n.use(initReactI18next).init({
  resources: { en, te, hi },
  lng: 'en',
  fallbackLng: 'en',
  interpolation: { escapeValue: false },
  parseMissingKeyHandler: (key) => {
    if (!key) return key;
    let formatted = key.replace(/_/g, ' ');
    formatted = formatted.charAt(0).toUpperCase() + formatted.slice(1);
    if (formatted.endsWith('.')) {
      formatted = formatted.slice(0, -1);
    }
    return formatted;
  },
});

export default i18n;
